// This file is auto-generated by @hey-api/openapi-ts

export const CreateGameRequestSchema = {
  type: "object",
  properties: {
    boardSize: {
      type: "integer",
      format: "int32",
    },
  },
  additionalProperties: false,
} as const;

export const CreatePlayerRequestSchema = {
  type: "object",
  properties: {
    id: {
      type: "string",
      nullable: true,
    },
  },
  additionalProperties: false,
} as const;

export const MakeMoveRequestSchema = {
  type: "object",
  properties: {
    x: {
      type: "integer",
      format: "int32",
    },
    y: {
      type: "integer",
      format: "int32",
    },
  },
  additionalProperties: false,
} as const;
