// This file is auto-generated by @hey-api/openapi-ts

export type CreateGameRequest = {
    boardSize?: number;
};

export type CreatePlayerRequest = {
    id?: (string) | null;
};

export type MakeMoveRequest = {
    x?: number;
    y?: number;
};

export type GetApiV2GameByGameIdData = {
    headers: {
        'X-Version': string;
    };
    path: {
        gameId: string;
    };
};

export type GetApiV2GameByGameIdResponse = (unknown);

export type GetApiV2GameByGameIdError = unknown;

export type GetApiV2GamesData = {
    headers: {
        'X-Version': string;
    };
};

export type GetApiV2GamesResponse = (unknown);

export type GetApiV2GamesError = unknown;

export type PostApiV2GameData = {
    body?: CreateGameRequest;
    headers: {
        'X-Version': string;
    };
};

export type PostApiV2GameResponse = (unknown);

export type PostApiV2GameError = unknown;

export type PostApiV2GameByGameIdJoinByPlayerIdData = {
    headers: {
        'X-Version': string;
    };
    path: {
        gameId: string;
        playerId: string;
    };
};

export type PostApiV2GameByGameIdJoinByPlayerIdResponse = (unknown);

export type PostApiV2GameByGameIdJoinByPlayerIdError = unknown;

export type PostApiV2GameByGameIdMakeMoveByPlayerIdData = {
    body?: MakeMoveRequest;
    headers: {
        'X-Version': string;
    };
    path: {
        gameId: string;
        playerId: string;
    };
};

export type PostApiV2GameByGameIdMakeMoveByPlayerIdResponse = (unknown);

export type PostApiV2GameByGameIdMakeMoveByPlayerIdError = unknown;

export type PostApiV2PlayersData = {
    body?: CreatePlayerRequest;
    headers: {
        'X-Version': string;
    };
};

export type PostApiV2PlayersResponse = (unknown);

export type PostApiV2PlayersError = unknown;