// This file is auto-generated by @hey-api/openapi-ts

export type CreateGameRequest = {
  boardSize?: number;
};

export type CreatePlayerRequest = {
  id?: string | null;
};

export type Game = {
  readonly gameId?: string | null;
  gameBoard?: GameBoard;
  readonly playersMoves?: Array<Tile> | null;
  playerOne?: Player;
  playerTwo?: Player;
  readonly isGameStarted?: boolean;
  winnerId?: string | null;
};

export type GameBoard = {
  readonly lastPlacementById?: string | null;
};

export type MakeMoveRequest = {
  x?: number;
  y?: number;
};

export type Player = {
  id?: string | null;
};

export type Tile = {
  x?: number;
  y?: number;
};

export type TilePlacementResult = {
  isValid?: boolean;
  validationError?: TilePlacementValidationError;
  winnerId?: string | null;
};

export type TilePlacementValidationError = 0 | 1 | 2 | 3 | 4 | 5;

export const TilePlacementValidationError = {
  _0: 0,
  _1: 1,
  _2: 2,
  _3: 3,
  _4: 4,
  _5: 5,
} as const;

export type GetApiV2GameByGameIdData = {
  headers: {
    "X-Version": string;
  };
  path: {
    gameId: string;
  };
};

export type GetApiV2GameByGameIdResponse = Game;

export type GetApiV2GameByGameIdError = unknown;

export type GetApiV2GamesData = {
  headers: {
    "X-Version": string;
  };
};

export type GetApiV2GamesResponse = Array<Game>;

export type GetApiV2GamesError = unknown;

export type PostApiV2GameData = {
  body?: CreateGameRequest;
  headers: {
    "X-Version": string;
  };
};

export type PostApiV2GameResponse = Game;

export type PostApiV2GameError = unknown;

export type PostApiV2GameByGameIdJoinByPlayerIdData = {
  headers: {
    "X-Version": string;
  };
  path: {
    gameId: string;
    playerId: string;
  };
};

export type PostApiV2GameByGameIdJoinByPlayerIdResponse = unknown;

export type PostApiV2GameByGameIdJoinByPlayerIdError = unknown;

export type PostApiV2GameByGameIdMakeMoveByPlayerIdData = {
  body?: MakeMoveRequest;
  headers: {
    "X-Version": string;
  };
  path: {
    gameId: string;
    playerId: string;
  };
};

export type PostApiV2GameByGameIdMakeMoveByPlayerIdResponse =
  TilePlacementResult;

export type PostApiV2GameByGameIdMakeMoveByPlayerIdError = unknown;

export type PostApiV2PlayersData = {
  body?: CreatePlayerRequest;
  headers: {
    "X-Version": string;
  };
};

export type PostApiV2PlayersResponse = unknown;

export type PostApiV2PlayersError = unknown;
