// This file is auto-generated by @hey-api/openapi-ts

export type CreateGameRequest = {
  boardSize: number;
};

export type CreateGameResponse = {
  gameId: string;
};

export type CreatePlayerRequest = {
  id: string;
};

export type GameMoveDto = {
  tile: TileDto;
  playerId: string;
  moveNumber: number;
};

export type GetAvailableGamesResponse = {
  gameId: string;
};

export type GetGameResponse = {
  gameId: string;
  playerOne?: PlayerDto;
  playerTwo?: PlayerDto;
  hasBothPlayersJoined: boolean;
  isGameStarted: boolean;
  nextMoveShouldMakePlayerId?: string | null;
  winnerId?: string | null;
  winningSequence?: Array<TileDto> | null;
  playersMoves: Array<GameMoveDto>;
};

export type MakeMoveRequest = {
  x: number;
  y: number;
};

export type PlaceTileResponse = {
  winningSequence?: Array<TileDto> | null;
  readonly isWinningMove?: boolean;
};

export type PlayerDto = {
  playerId: string;
};

export type ProblemDetails = {
  type?: string | null;
  title?: string | null;
  status?: number | null;
  detail?: string | null;
  instance?: string | null;
  [key: string]: (unknown | string | number) | undefined;
};

export type TileDto = {
  x: number;
  y: number;
};

export type GetApiV2GameByGameIdData = {
  headers: {
    "X-Version": string;
  };
  path: {
    gameId: string;
  };
};

export type GetApiV2GameByGameIdResponse = GetGameResponse;

export type GetApiV2GameByGameIdError = ProblemDetails;

export type GetApiV2GamesData = {
  headers: {
    "X-Version": string;
  };
};

export type GetApiV2GamesResponse = Array<GetAvailableGamesResponse>;

export type GetApiV2GamesError = unknown;

export type PostApiV2GameData = {
  body?: CreateGameRequest;
  headers: {
    "X-Version": string;
  };
};

export type PostApiV2GameResponse = CreateGameResponse;

export type PostApiV2GameError = ProblemDetails;

export type PostApiV2GameByGameIdJoinByPlayerIdData = {
  headers: {
    "X-Version": string;
  };
  path: {
    gameId: string;
    playerId: string;
  };
};

export type PostApiV2GameByGameIdJoinByPlayerIdResponse = unknown;

export type PostApiV2GameByGameIdJoinByPlayerIdError = ProblemDetails;

export type PostApiV2GameByGameIdMakeMoveByPlayerIdData = {
  body?: MakeMoveRequest;
  headers: {
    "X-Version": string;
  };
  path: {
    gameId: string;
    playerId: string;
  };
};

export type PostApiV2GameByGameIdMakeMoveByPlayerIdResponse = PlaceTileResponse;

export type PostApiV2GameByGameIdMakeMoveByPlayerIdError = ProblemDetails;

export type PostApiV2PlayersData = {
  body?: CreatePlayerRequest;
  headers: {
    "X-Version": string;
  };
};

export type PostApiV2PlayersResponse = unknown;

export type PostApiV2PlayersError = unknown;
