version: '3.8'

services:
  gomoku-server:
    build:
      context: ..
      dockerfile: ./GomokuServer/Dockerfile
    ports:
      - "8080:8080"
    networks:
      - gomoku-network
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_URLS: http://+:8080
      RAPFI_ENGINE_URL: http://rapfi:5000

  rapfi:
    build:
      context: ./GomokuAI
      dockerfile: Dockerfile
    networks:
      - gomoku-network
    command: ["./build/rapfi"]

networks:
  gomoku-network:
    driver: bridge
