version: '3.8'

services:
  gomoku-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080" # Ваш текущий сервер
    networks:
      - gomoku-ai-network

  gomoku-ai:
    build:
      context: ./GomokuAI
      dockerfile: Dockerfile
    networks:
      - gomoku-ai-network
    command: ["./build/rapfi"] # Точка входа в Rapfi

networks:
  gomoku-ai-network:
    driver: bridge
