// This file is auto-generated by @hey-api/openapi-ts

export type GameInfo = {
  gameId?: number;
  yourTurn?: boolean;
};

export type Move = {
  gameId?: number;
  player?: string | null;
  row?: number;
  column?: number;
};

export type GetApiV1GameData = {
  headers?: {
    "X-Version"?: string;
  };
};

export type GetApiV1GameResponse = GameInfo;

export type GetApiV1GameError = unknown;

export type PostApiV1GameData = {
  body?: Move;
  headers?: {
    "X-Version"?: string;
  };
};

export type PostApiV1GameResponse = boolean;

export type PostApiV1GameError = unknown;

export type GetApiV1GameByGameIdData = {
  headers?: {
    "X-Version"?: string;
  };
  path: {
    gameId: number;
  };
};

export type GetApiV1GameByGameIdResponse = Move;

export type GetApiV1GameByGameIdError = unknown;
