export type { GetApiGameAnonymousActiveQueryKey } from "./useGetApiGameAnonymousActive.ts";
export type { GetApiGameAnonymousActiveSuspenseQueryKey } from "./useGetApiGameAnonymousActiveSuspense.ts";
export type { GetApiGameAnonymousAvailableToJoinQueryKey } from "./useGetApiGameAnonymousAvailableToJoin.ts";
export type { GetApiGameAnonymousAvailableToJoinSuspenseQueryKey } from "./useGetApiGameAnonymousAvailableToJoinSuspense.ts";
export type { GetApiGameAnonymousGameidHistoryQueryKey } from "./useGetApiGameAnonymousGameidHistory.ts";
export type { GetApiGameAnonymousGameidHistorySuspenseQueryKey } from "./useGetApiGameAnonymousGameidHistorySuspense.ts";
export type { GetApiGameRegisteredActiveQueryKey } from "./useGetApiGameRegisteredActive.ts";
export type { GetApiGameRegisteredActiveSuspenseQueryKey } from "./useGetApiGameRegisteredActiveSuspense.ts";
export type { GetApiGameRegisteredAvailableToJoinQueryKey } from "./useGetApiGameRegisteredAvailableToJoin.ts";
export type { GetApiGameRegisteredAvailableToJoinSuspenseQueryKey } from "./useGetApiGameRegisteredAvailableToJoinSuspense.ts";
export type { GetApiGameRegisteredGameidHistoryQueryKey } from "./useGetApiGameRegisteredGameidHistory.ts";
export type { GetApiGameRegisteredGameidHistorySuspenseQueryKey } from "./useGetApiGameRegisteredGameidHistorySuspense.ts";
export type { GetApiProfilesUsernameGamesQueryKey } from "./useGetApiProfilesUsernameGames.ts";
export type { GetApiProfilesUsernameGamesSuspenseQueryKey } from "./useGetApiProfilesUsernameGamesSuspense.ts";
export type { GetApiV1RapfiTestQueryKey } from "./useGetApiV1RapfiTest.ts";
export type { GetApiV1RapfiTestSuspenseQueryKey } from "./useGetApiV1RapfiTestSuspense.ts";
export type { GetHealthQueryKey } from "./useGetHealth.ts";
export type { GetHealthSuspenseQueryKey } from "./useGetHealthSuspense.ts";
export type { PostApiGameAnonymousMutationKey } from "./usePostApiGameAnonymous.ts";
export type { PostApiGameAnonymousGameidJoinMutationKey } from "./usePostApiGameAnonymousGameidJoin.ts";
export type { PostApiGameRegisteredMutationKey } from "./usePostApiGameRegistered.ts";
export type { PostApiGameRegisteredGameidJoinMutationKey } from "./usePostApiGameRegisteredGameidJoin.ts";
export type { PostGamehubAnonymousApproverematchMutationKey } from "./usePostGamehubAnonymousApproverematch.ts";
export type { PostGamehubAnonymousApproveundoMutationKey } from "./usePostGamehubAnonymousApproveundo.ts";
export type { PostGamehubAnonymousGetclockMutationKey } from "./usePostGamehubAnonymousGetclock.ts";
export type { PostGamehubAnonymousJoingamegroupMutationKey } from "./usePostGamehubAnonymousJoingamegroup.ts";
export type { PostGamehubAnonymousMakemoveMutationKey } from "./usePostGamehubAnonymousMakemove.ts";
export type { PostGamehubAnonymousRequestrematchMutationKey } from "./usePostGamehubAnonymousRequestrematch.ts";
export type { PostGamehubAnonymousRequestundoMutationKey } from "./usePostGamehubAnonymousRequestundo.ts";
export type { PostGamehubAnonymousResignMutationKey } from "./usePostGamehubAnonymousResign.ts";
export type { PostGamehubAnonymousSendinvitationtoplayMutationKey } from "./usePostGamehubAnonymousSendinvitationtoplay.ts";
export type { PostGamehubAnonymousSendmessageMutationKey } from "./usePostGamehubAnonymousSendmessage.ts";
export type { PostGamehubRegisteredApproverematchMutationKey } from "./usePostGamehubRegisteredApproverematch.ts";
export type { PostGamehubRegisteredApproveundoMutationKey } from "./usePostGamehubRegisteredApproveundo.ts";
export type { PostGamehubRegisteredGetclockMutationKey } from "./usePostGamehubRegisteredGetclock.ts";
export type { PostGamehubRegisteredJoingamegroupMutationKey } from "./usePostGamehubRegisteredJoingamegroup.ts";
export type { PostGamehubRegisteredMakemoveMutationKey } from "./usePostGamehubRegisteredMakemove.ts";
export type { PostGamehubRegisteredRequestrematchMutationKey } from "./usePostGamehubRegisteredRequestrematch.ts";
export type { PostGamehubRegisteredRequestundoMutationKey } from "./usePostGamehubRegisteredRequestundo.ts";
export type { PostGamehubRegisteredResignMutationKey } from "./usePostGamehubRegisteredResign.ts";
export type { PostGamehubRegisteredSendinvitationtoplayMutationKey } from "./usePostGamehubRegisteredSendinvitationtoplay.ts";
export type { PostGamehubRegisteredSendmessageMutationKey } from "./usePostGamehubRegisteredSendmessage.ts";
export { getApiGameAnonymousActiveQueryKey, getApiGameAnonymousActiveQueryOptions, useGetApiGameAnonymousActive } from "./useGetApiGameAnonymousActive.ts";
export { getApiGameAnonymousActiveSuspenseQueryKey, getApiGameAnonymousActiveSuspenseQueryOptions, useGetApiGameAnonymousActiveSuspense } from "./useGetApiGameAnonymousActiveSuspense.ts";
export { getApiGameAnonymousAvailableToJoinQueryKey, getApiGameAnonymousAvailableToJoinQueryOptions, useGetApiGameAnonymousAvailableToJoin } from "./useGetApiGameAnonymousAvailableToJoin.ts";
export { getApiGameAnonymousAvailableToJoinSuspenseQueryKey, getApiGameAnonymousAvailableToJoinSuspenseQueryOptions, useGetApiGameAnonymousAvailableToJoinSuspense } from "./useGetApiGameAnonymousAvailableToJoinSuspense.ts";
export { getApiGameAnonymousGameidHistoryQueryKey, getApiGameAnonymousGameidHistoryQueryOptions, useGetApiGameAnonymousGameidHistory } from "./useGetApiGameAnonymousGameidHistory.ts";
export { getApiGameAnonymousGameidHistorySuspenseQueryKey, getApiGameAnonymousGameidHistorySuspenseQueryOptions, useGetApiGameAnonymousGameidHistorySuspense } from "./useGetApiGameAnonymousGameidHistorySuspense.ts";
export { getApiGameRegisteredActiveQueryKey, getApiGameRegisteredActiveQueryOptions, useGetApiGameRegisteredActive } from "./useGetApiGameRegisteredActive.ts";
export { getApiGameRegisteredActiveSuspenseQueryKey, getApiGameRegisteredActiveSuspenseQueryOptions, useGetApiGameRegisteredActiveSuspense } from "./useGetApiGameRegisteredActiveSuspense.ts";
export { getApiGameRegisteredAvailableToJoinQueryKey, getApiGameRegisteredAvailableToJoinQueryOptions, useGetApiGameRegisteredAvailableToJoin } from "./useGetApiGameRegisteredAvailableToJoin.ts";
export { getApiGameRegisteredAvailableToJoinSuspenseQueryKey, getApiGameRegisteredAvailableToJoinSuspenseQueryOptions, useGetApiGameRegisteredAvailableToJoinSuspense } from "./useGetApiGameRegisteredAvailableToJoinSuspense.ts";
export { getApiGameRegisteredGameidHistoryQueryKey, getApiGameRegisteredGameidHistoryQueryOptions, useGetApiGameRegisteredGameidHistory } from "./useGetApiGameRegisteredGameidHistory.ts";
export { getApiGameRegisteredGameidHistorySuspenseQueryKey, getApiGameRegisteredGameidHistorySuspenseQueryOptions, useGetApiGameRegisteredGameidHistorySuspense } from "./useGetApiGameRegisteredGameidHistorySuspense.ts";
export { getApiProfilesUsernameGamesQueryKey, getApiProfilesUsernameGamesQueryOptions, useGetApiProfilesUsernameGames } from "./useGetApiProfilesUsernameGames.ts";
export { getApiProfilesUsernameGamesSuspenseQueryKey, getApiProfilesUsernameGamesSuspenseQueryOptions, useGetApiProfilesUsernameGamesSuspense } from "./useGetApiProfilesUsernameGamesSuspense.ts";
export { getApiV1RapfiTestQueryKey, getApiV1RapfiTestQueryOptions, useGetApiV1RapfiTest } from "./useGetApiV1RapfiTest.ts";
export { getApiV1RapfiTestSuspenseQueryKey, getApiV1RapfiTestSuspenseQueryOptions, useGetApiV1RapfiTestSuspense } from "./useGetApiV1RapfiTestSuspense.ts";
export { getHealthQueryKey, getHealthQueryOptions, useGetHealth } from "./useGetHealth.ts";
export { getHealthSuspenseQueryKey, getHealthSuspenseQueryOptions, useGetHealthSuspense } from "./useGetHealthSuspense.ts";
export { postApiGameAnonymousMutationKey, usePostApiGameAnonymous } from "./usePostApiGameAnonymous.ts";
export { postApiGameAnonymousGameidJoinMutationKey, usePostApiGameAnonymousGameidJoin } from "./usePostApiGameAnonymousGameidJoin.ts";
export { postApiGameRegisteredMutationKey, usePostApiGameRegistered } from "./usePostApiGameRegistered.ts";
export { postApiGameRegisteredGameidJoinMutationKey, usePostApiGameRegisteredGameidJoin } from "./usePostApiGameRegisteredGameidJoin.ts";
export { postGamehubAnonymousApproverematchMutationKey, usePostGamehubAnonymousApproverematch } from "./usePostGamehubAnonymousApproverematch.ts";
export { postGamehubAnonymousApproveundoMutationKey, usePostGamehubAnonymousApproveundo } from "./usePostGamehubAnonymousApproveundo.ts";
export { postGamehubAnonymousGetclockMutationKey, usePostGamehubAnonymousGetclock } from "./usePostGamehubAnonymousGetclock.ts";
export { postGamehubAnonymousJoingamegroupMutationKey, usePostGamehubAnonymousJoingamegroup } from "./usePostGamehubAnonymousJoingamegroup.ts";
export { postGamehubAnonymousMakemoveMutationKey, usePostGamehubAnonymousMakemove } from "./usePostGamehubAnonymousMakemove.ts";
export { postGamehubAnonymousRequestrematchMutationKey, usePostGamehubAnonymousRequestrematch } from "./usePostGamehubAnonymousRequestrematch.ts";
export { postGamehubAnonymousRequestundoMutationKey, usePostGamehubAnonymousRequestundo } from "./usePostGamehubAnonymousRequestundo.ts";
export { postGamehubAnonymousResignMutationKey, usePostGamehubAnonymousResign } from "./usePostGamehubAnonymousResign.ts";
export { postGamehubAnonymousSendinvitationtoplayMutationKey, usePostGamehubAnonymousSendinvitationtoplay } from "./usePostGamehubAnonymousSendinvitationtoplay.ts";
export { postGamehubAnonymousSendmessageMutationKey, usePostGamehubAnonymousSendmessage } from "./usePostGamehubAnonymousSendmessage.ts";
export { postGamehubRegisteredApproverematchMutationKey, usePostGamehubRegisteredApproverematch } from "./usePostGamehubRegisteredApproverematch.ts";
export { postGamehubRegisteredApproveundoMutationKey, usePostGamehubRegisteredApproveundo } from "./usePostGamehubRegisteredApproveundo.ts";
export { postGamehubRegisteredGetclockMutationKey, usePostGamehubRegisteredGetclock } from "./usePostGamehubRegisteredGetclock.ts";
export { postGamehubRegisteredJoingamegroupMutationKey, usePostGamehubRegisteredJoingamegroup } from "./usePostGamehubRegisteredJoingamegroup.ts";
export { postGamehubRegisteredMakemoveMutationKey, usePostGamehubRegisteredMakemove } from "./usePostGamehubRegisteredMakemove.ts";
export { postGamehubRegisteredRequestrematchMutationKey, usePostGamehubRegisteredRequestrematch } from "./usePostGamehubRegisteredRequestrematch.ts";
export { postGamehubRegisteredRequestundoMutationKey, usePostGamehubRegisteredRequestundo } from "./usePostGamehubRegisteredRequestundo.ts";
export { postGamehubRegisteredResignMutationKey, usePostGamehubRegisteredResign } from "./usePostGamehubRegisteredResign.ts";
export { postGamehubRegisteredSendinvitationtoplayMutationKey, usePostGamehubRegisteredSendinvitationtoplay } from "./usePostGamehubRegisteredSendinvitationtoplay.ts";
export { postGamehubRegisteredSendmessageMutationKey, usePostGamehubRegisteredSendmessage } from "./usePostGamehubRegisteredSendmessage.ts";