// This file is auto-generated by @hey-api/openapi-ts

export const ChatMessageClientMessageSchema = {
  required: ["gameId", "message", "user"],
  type: "object",
  properties: {
    gameId: {
      minLength: 1,
      type: "string",
    },
    user: {
      minLength: 1,
      type: "string",
    },
    message: {
      minLength: 1,
      type: "string",
    },
  },
  additionalProperties: false,
} as const;

export const CreateGameRequestSchema = {
  required: ["boardSize"],
  type: "object",
  properties: {
    boardSize: {
      type: "integer",
      format: "int32",
    },
  },
  additionalProperties: false,
} as const;

export const CreateGameResponseSchema = {
  required: ["gameId"],
  type: "object",
  properties: {
    gameId: {
      minLength: 1,
      type: "string",
    },
  },
  additionalProperties: false,
} as const;

export const GetAvailableGamesResponseSchema = {
  required: ["gameId", "opponent"],
  type: "object",
  properties: {
    gameId: {
      minLength: 1,
      type: "string",
    },
    opponent: {
      $ref: "#/components/schemas/PlayerDto",
    },
  },
  additionalProperties: false,
} as const;

export const GetGameHistoryResponseSchema = {
  required: ["boardSize", "movesCount", "movesHistory", "players"],
  type: "object",
  properties: {
    boardSize: {
      type: "integer",
      format: "int32",
    },
    movesCount: {
      type: "integer",
      format: "int32",
    },
    players: {
      $ref: "#/components/schemas/UsernamesDto",
    },
    movesHistory: {
      type: "object",
      additionalProperties: {
        $ref: "#/components/schemas/TileDto",
      },
    },
  },
  additionalProperties: false,
} as const;

export const MakeMoveClientMessageSchema = {
  required: ["gameId", "x", "y"],
  type: "object",
  properties: {
    gameId: {
      minLength: 1,
      type: "string",
    },
    x: {
      type: "integer",
      format: "int32",
    },
    y: {
      type: "integer",
      format: "int32",
    },
  },
  additionalProperties: false,
} as const;

export const PlayerDtoSchema = {
  required: ["playerId", "userName"],
  type: "object",
  properties: {
    playerId: {
      minLength: 1,
      type: "string",
    },
    userName: {
      minLength: 1,
      type: "string",
    },
    color: {
      type: "string",
      nullable: true,
    },
  },
  additionalProperties: false,
} as const;

export const ProblemDetailsSchema = {
  type: "object",
  properties: {
    type: {
      type: "string",
      nullable: true,
    },
    title: {
      type: "string",
      nullable: true,
    },
    status: {
      type: "integer",
      format: "int32",
      nullable: true,
    },
    detail: {
      type: "string",
      nullable: true,
    },
    instance: {
      type: "string",
      nullable: true,
    },
  },
  additionalProperties: {},
} as const;

export const TileDtoSchema = {
  required: ["x", "y"],
  type: "object",
  properties: {
    x: {
      type: "integer",
      format: "int32",
    },
    y: {
      type: "integer",
      format: "int32",
    },
  },
  additionalProperties: false,
} as const;

export const UsernamesDtoSchema = {
  type: "object",
  properties: {
    black: {
      type: "string",
      nullable: true,
    },
    white: {
      type: "string",
      nullable: true,
    },
  },
  additionalProperties: false,
} as const;
