// This file is auto-generated by @hey-api/openapi-ts

import {
  createClient,
  createConfig,
  type Options,
} from "@hey-api/client-fetch";
import type {
  GetApiAuthInfoData,
  GetApiAuthInfoError,
  GetApiAuthInfoResponse,
  GetApiGameByGameIdData,
  GetApiGameByGameIdError,
  GetApiGameByGameIdResponse,
  GetApiGamesData,
  GetApiGamesError,
  GetApiGamesResponse,
  PostApiGameData,
  PostApiGameError,
  PostApiGameResponse,
  PostApiGameByGameIdJoinData,
  PostApiGameByGameIdJoinError,
  PostApiGameByGameIdJoinResponse,
  PostApiGameByGameIdMakeMoveData,
  PostApiGameByGameIdMakeMoveError,
  PostApiGameByGameIdMakeMoveResponse,
  GetHealthData,
  GetHealthError,
  GetHealthResponse,
  PostGamehubJoinGameGroupData,
  PostGamehubMakeMoveData,
  PostGamehubSendMessageData,
  PostGamehubReceiveMessageData,
} from "./types.gen";

export const client = createClient(createConfig());

/**
 * Get auth user information
 */
export const getApiAuthInfo = <ThrowOnError extends boolean = false>(
  options: Options<GetApiAuthInfoData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    GetApiAuthInfoResponse,
    GetApiAuthInfoError,
    ThrowOnError
  >({
    ...options,
    url: "/api/auth/info",
  });
};

/**
 * Get information about game by game id
 */
export const getApiGameByGameId = <ThrowOnError extends boolean = false>(
  options: Options<GetApiGameByGameIdData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    GetApiGameByGameIdResponse,
    GetApiGameByGameIdError,
    ThrowOnError
  >({
    ...options,
    url: "/api/game/{gameId}",
  });
};

/**
 * Get all games, which are available to join
 */
export const getApiGames = <ThrowOnError extends boolean = false>(
  options: Options<GetApiGamesData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    GetApiGamesResponse,
    GetApiGamesError,
    ThrowOnError
  >({
    ...options,
    url: "/api/games",
  });
};

/**
 * Create new game
 */
export const postApiGame = <ThrowOnError extends boolean = false>(
  options: Options<PostApiGameData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    PostApiGameResponse,
    PostApiGameError,
    ThrowOnError
  >({
    ...options,
    url: "/api/game",
  });
};

/**
 * Join game
 */
export const postApiGameByGameIdJoin = <ThrowOnError extends boolean = false>(
  options: Options<PostApiGameByGameIdJoinData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    PostApiGameByGameIdJoinResponse,
    PostApiGameByGameIdJoinError,
    ThrowOnError
  >({
    ...options,
    url: "/api/game/{gameId}/join",
  });
};

/**
 * Make move in a game
 */
export const postApiGameByGameIdMakeMove = <
  ThrowOnError extends boolean = false,
>(
  options: Options<PostApiGameByGameIdMakeMoveData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    PostApiGameByGameIdMakeMoveResponse,
    PostApiGameByGameIdMakeMoveError,
    ThrowOnError
  >({
    ...options,
    url: "/api/game/{gameId}/make-move",
  });
};

/**
 * Health check endpoint
 */
export const getHealth = <ThrowOnError extends boolean = false>(
  options: Options<GetHealthData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    GetHealthResponse,
    GetHealthError,
    ThrowOnError
  >({
    ...options,
    url: "/health",
  });
};

export const postGamehubJoinGameGroup = <ThrowOnError extends boolean = false>(
  options?: Options<PostGamehubJoinGameGroupData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<void, unknown, ThrowOnError>({
    ...options,
    url: "/gamehub/JoinGameGroup",
  });
};

export const postGamehubMakeMove = <ThrowOnError extends boolean = false>(
  options?: Options<PostGamehubMakeMoveData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<void, unknown, ThrowOnError>({
    ...options,
    url: "/gamehub/MakeMove",
  });
};

export const postGamehubSendMessage = <ThrowOnError extends boolean = false>(
  options?: Options<PostGamehubSendMessageData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<void, unknown, ThrowOnError>({
    ...options,
    url: "/gamehub/SendMessage",
  });
};

export const postGamehubReceiveMessage = <ThrowOnError extends boolean = false>(
  options?: Options<PostGamehubReceiveMessageData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<void, unknown, ThrowOnError>({
    ...options,
    url: "/gamehub/ReceiveMessage",
  });
};
