/* THIS (.ts) FILE IS GENERATED BY Tapper */
/* eslint-disable */
/* tslint:disable */
import type { TimeControlDto } from "./GomokuServer.Application.Games.Dto";

/** Transpiled from GomokuServer.Api.GameOptions */
export type GameOptions = {
  /** Transpiled from int */
  boardSize: number;
  /** Transpiled from GomokuServer.Application.Games.Dto.TimeControlDto */
  timeControl: TimeControlDto;
  /** Transpiled from bool */
  anonymous: boolean;
};
