/* THIS (.ts) FILE IS GENERATED BY Tapper */
 
/* tslint:disable */

/** Transpiled from GomokuServer.Application.Games.Dto.TileDto */
export type TileDto = {
  /** Transpiled from int */
  x: number;
  /** Transpiled from int */
  y: number;
};
