/* THIS (.ts) FILE IS GENERATED BY Tapper */
/* eslint-disable */
/* tslint:disable */
import type { TileDto } from "./GomokuServer.Application.Games.Dto";

/** Transpiled from GomokuServer.Api.Hubs.Messages.Server.ErrorMessage */
export type ErrorMessage = {
  /** Transpiled from string */
  message: string;
};

/** Transpiled from GomokuServer.Api.Hubs.Messages.Server.GameIsOverMessage */
export type GameIsOverMessage = {
  /** Transpiled from string */
  result: string;
  /** Transpiled from System.Collections.Generic.List<GomokuServer.Application.Games.Dto.TileDto>? */
  winningSequence?: TileDto[];
};

/** Transpiled from GomokuServer.Api.Hubs.Messages.Server.GameStartedMessage */
export type GameStartedMessage = {
  /** Transpiled from bool */
  isMyMoveFirst: boolean;
};

/** Transpiled from GomokuServer.Api.Hubs.Messages.Server.PlayerJoinedGameMessage */
export type PlayerJoinedGameMessage = {
  /** Transpiled from string */
  userId: string;
};

/** Transpiled from GomokuServer.Api.Hubs.Messages.Server.PlayerMadeMoveMessage */
export type PlayerMadeMoveMessage = {
  /** Transpiled from string */
  playerId: string;
  /** Transpiled from GomokuServer.Application.Games.Dto.TileDto */
  tile: TileDto;
  /** Transpiled from string */
  placedTileColor: string;
};

/** Transpiled from GomokuServer.Api.Hubs.Messages.Server.RematchApprovedMessage */
export type RematchApprovedMessage = {
  /** Transpiled from string */
  newGameId: string;
};
