namespace GomokuServer.Application.Games.Queries;

public record GetAvailableToJoinRegisteredGamesQuery : GetAvailableToJoinGamesQuery;

public class GetAvailableToJoinRegisteredGamesQueryHandler(IRegisteredPlayersAwaitingGameRepository _registeredPlayersAwaitingGameRepository)
	: GetAvailableToJoinGamesQueryHandler<GetAvailableToJoinRegisteredGamesQuery>(_registeredPlayersAwaitingGameRepository);

public record GetAvailableToJoinAnonymousGamesQuery : GetAvailableToJoinGamesQuery;

public class GetAvailableToJoinAnonymousGamesQueryHandler(IAnonymousPlayersAwaitingGameRepository _anonymousPlayersAwaitingGameRepository)
	: GetAvailableToJoinGamesQueryHandler<GetAvailableToJoinAnonymousGamesQuery>(_anonymousPlayersAwaitingGameRepository);
