namespace GomokuServer.Application.Games.Queries;

public record GetAvailableToJoinRegisteredGamesQuery : GetAvailableToJoinGamesQuery;

public class GetAvailableToJoinRegisteredGamesQueryHandler(IRegisteredAwaitingPlayersGamesRepository _registeredAwaitingPlayersGamesRepository)
	: GetAvailableToJoinGamesQueryHandler<GetAvailableToJoinRegisteredGamesQuery>(_registeredAwaitingPlayersGamesRepository);

public record GetAvailableToJoinAnonymousGamesQuery : GetAvailableToJoinGamesQuery;

public class GetAvailableToJoinAnonymousGamesQueryHandler(IAnonymousAwaitingPlayersGamesRepository _anonymousAwaitingPlayersGamesRepository)
	: GetAvailableToJoinGamesQueryHandler<GetAvailableToJoinAnonymousGamesQuery>(_anonymousAwaitingPlayersGamesRepository);
