namespace GomokuServer.Application.Games.Queries;

public record GetActiveRegisteredGamesQuery : GetActiveGamesQuery;

public class GetActiveRegisteredGamesQueryHandler(IRegisteredGamesRepository _registeredGamesRepository)
	: GetActiveGamesQueryHandler<GetActiveRegisteredGamesQuery>(_registeredGamesRepository);
