
var Rapfi = (() => {
  var _scriptName = typeof document != 'undefined' ? document.currentScript?.src : undefined;
  if (typeof __filename != 'undefined') _scriptName = _scriptName || __filename;
  return (
function(moduleArg = {}) {
  var moduleRtn;

var g=moduleArg,aa,ba,ca=new Promise((a,b)=>{aa=a;ba=b}),da="object"==typeof window,ea="undefined"!=typeof WorkerGlobalScope,fa="object"==typeof process&&"object"==typeof process.versions&&"string"==typeof process.versions.node&&"renderer"!=process.type;g.expectedDataFileDownloads??(g.expectedDataFileDownloads=0);g.expectedDataFileDownloads++;
(()=>{var a="undefined"!=typeof ENVIRONMENT_IS_WASM_WORKER&&ENVIRONMENT_IS_WASM_WORKER;if(!("undefined"!=typeof ENVIRONMENT_IS_PTHREAD&&ENVIRONMENT_IS_PTHREAD||a)){var b="object"===typeof process&&"object"===typeof process.versions&&"string"===typeof process.versions.node;(function(c){function d(l,q,z,B){b?require("fs").readFile(l,(t,r)=>{t?B(t):z(r.buffer)}):(g.dataFileDownloads??(g.dataFileDownloads={}),fetch(l).catch(t=>Promise.reject(Error(`Network Error: ${l}`,{cause:t}))).then(t=>{if(!t.ok)return Promise.reject(Error(`${t.status}: ${t.url}`));
if(!t.body&&t.arrayBuffer)return t.arrayBuffer().then(z);const r=t.body.getReader(),A=()=>r.read().then(K).catch(R=>Promise.reject(Error(`Unexpected error while handling : ${t.url} ${R}`,{cause:R}))),H=[],M=Number(t.headers.get("Content-Length")??q);let ya=0;const K=({done:R,value:tb})=>{if(R){var ka=new Uint8Array(H.map(Ta=>Ta.length).reduce((Ta,Dc)=>Ta+Dc,0));R=0;for(var la of H)ka.set(la,R),R+=la.length;z(ka.buffer)}else{H.push(tb);ya+=tb.length;g.dataFileDownloads[l]={loaded:ya,total:M};R=la=
0;for(ka of Object.values(g.dataFileDownloads))la+=ka.loaded,R+=ka.total;g.setStatus?.(`Downloading data... (${la}/${R})`);return A()}};g.setStatus?.("Downloading data...");return A()}))}function e(l){console.error("package error:",l)}function f(l){function q(r,A,H){this.start=r;this.end=A;this.audio=H}function z(r){if(!r)throw"Loading data file failed."+Error().stack;if(r.constructor.name!==ArrayBuffer.name)throw"bad input to processPackageData"+Error().stack;r=new Uint8Array(r);q.prototype.kb=r;
r=c.files;for(var A=0;A<r.length;++A)q.prototype.Za[r[A].filename].onload();l.removeRunDependency("datafile_rapfi-single.data")}q.prototype={Za:{},open:function(r,A){this.name=A;this.Za[A]=this;l.addRunDependency(`fp ${this.name}`)},send:function(){},onload:function(){this.jb(this.kb.subarray(this.start,this.end))},jb:function(r){l.FS_createDataFile(this.name,null,r,!0,!0,!0);l.removeRunDependency(`fp ${this.name}`);this.Za[this.name]=null}};for(var B=c.files,t=0;t<B.length;++t)(new q(B[t].start,
B[t].end,B[t].audio||0)).open("GET",B[t].filename);l.addRunDependency("datafile_rapfi-single.data");l.preloadResults??(l.preloadResults={});l.preloadResults["rapfi-single.data"]={Ub:!1};n?(z(n),n=null):p=z}"object"===typeof window?window.encodeURIComponent(window.location.pathname.substring(0,window.location.pathname.lastIndexOf("/"))+"/"):"undefined"===typeof process&&"undefined"!==typeof location&&encodeURIComponent(location.pathname.substring(0,location.pathname.lastIndexOf("/"))+"/");var h=g.locateFile?
g.locateFile("rapfi-single.data",""):"rapfi-single.data",k=c.remote_package_size,p=null,n=g.getPreloadedPackage?g.getPreloadedPackage(h,k):null;n||d(h,k,l=>{p?(p(l),p=null):n=l},e);g.calledRun?f(g):(g.preRun??(g.preRun=[])).push(f)})({files:[{filename:"/config.toml",start:0,end:6505},{filename:"/mix9litefreestyle_bs15.bin.lz4",start:6505,end:7626401},{filename:"/mix9litefreestyle_bsmix.bin.lz4",start:7626401,end:15163905},{filename:"/mix9literenju_bs15_black.bin.lz4",start:15163905,end:22858902},
{filename:"/mix9literenju_bs15_white.bin.lz4",start:22858902,end:30426105},{filename:"/mix9litestandard_bs15.bin.lz4",start:30426105,end:38132845},{filename:"/model210901.bin",start:38132845,end:38156049}],remote_package_size:38156049})}})();g.sendCommand=g.sendCommand||null;g.terminate=g.terminate||null;g.onReceiveStdout=g.onReceiveStdout||(a=>console.log(a));g.onReceiveStderr=g.onReceiveStderr||(a=>console.error(a));g.onExit=g.onExit||(a=>console.log("exited with code "+a));g.noExitRuntime=!0;
g.preRun||(g.preRun=[]);g.preRun.push(function(){var a="",b=0;let c="",d="";const e=g.onReceiveStdout,f=g.onReceiveStderr;ha(function(){return b<a.length?a.charCodeAt(b++):null},function(k){k&&10!=k?c+=String.fromCharCode(k):(e(c),c="")},function(k){k&&10!=k?d+=String.fromCharCode(k):(f(d),d="")});const h=g.cwrap("gomocupLoopOnce","number",[]);g.sendCommand=function(k){a=k+"\n";b=0;h()};g.terminate=function(){g._emscripten_force_exit(0)}});
var ia=Object.assign({},g),ja=[],ma="./this.program",na=(a,b)=>{throw b;},m="",oa,pa;
if(fa){var fs=require("fs");require("path");m=__dirname+"/";pa=a=>{a=qa(a)?new URL(a):a;return fs.readFileSync(a)};oa=async a=>{a=qa(a)?new URL(a):a;return fs.readFileSync(a,void 0)};!g.thisProgram&&1<process.argv.length&&(ma=process.argv[1].replace(/\\/g,"/"));ja=process.argv.slice(2);na=(a,b)=>{process.exitCode=a;throw b;}}else if(da||ea)ea?m=self.location.href:"undefined"!=typeof document&&document.currentScript&&(m=document.currentScript.src),_scriptName&&(m=_scriptName),m.startsWith("blob:")?
m="":m=m.substr(0,m.replace(/[?#].*/,"").lastIndexOf("/")+1),ea&&(pa=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),oa=async a=>{if(qa(a))return new Promise((c,d)=>{var e=new XMLHttpRequest;e.open("GET",a,!0);e.responseType="arraybuffer";e.onload=()=>{200==e.status||0==e.status&&e.response?c(e.response):d(e.status)};e.onerror=d;e.send(null)});var b=await fetch(a,{credentials:"same-origin"});if(b.ok)return b.arrayBuffer();
throw Error(b.status+" : "+b.url);};var ra=g.print||console.log.bind(console),sa=g.printErr||console.error.bind(console);Object.assign(g,ia);ia=null;g.arguments&&(ja=g.arguments);g.thisProgram&&(ma=g.thisProgram);var ta=g.wasmBinary,ua,va=!1,wa,u,v,xa,w,x;
function za(){var a=ua.buffer;g.HEAP8=u=new Int8Array(a);g.HEAP16=xa=new Int16Array(a);g.HEAPU8=v=new Uint8Array(a);g.HEAPU16=new Uint16Array(a);g.HEAP32=w=new Int32Array(a);g.HEAPU32=x=new Uint32Array(a);g.HEAPF32=new Float32Array(a);g.HEAPF64=new Float64Array(a)}g.wasmMemory?ua=g.wasmMemory:ua=new WebAssembly.Memory({initial:(g.INITIAL_MEMORY||16777216)/65536,maximum:32768});za();var Aa=[],Ba=[],Ca=[],Da=[],Ea=[],Fa=!1;function Ga(){var a=g.preRun.shift();Aa.unshift(a)}var Ha=0,Ia=null;
function Ja(){Ha++;g.monitorRunDependencies?.(Ha)}function Ka(){Ha--;g.monitorRunDependencies?.(Ha);if(0==Ha&&Ia){var a=Ia;Ia=null;a()}}function La(a){g.onAbort?.(a);a="Aborted("+a+")";sa(a);va=!0;a=new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");ba(a);throw a;}var Ma=a=>a.startsWith("data:application/octet-stream;base64,"),qa=a=>a.startsWith("file://"),Na;
async function Oa(a){if(!ta)try{var b=await oa(a);return new Uint8Array(b)}catch{}if(a==Na&&ta)a=new Uint8Array(ta);else if(pa)a=pa(a);else throw"both async and sync fetching of the wasm failed";return a}async function Pa(a,b){try{var c=await Oa(a);return await WebAssembly.instantiate(c,b)}catch(d){sa(`failed to asynchronously prepare wasm: ${d}`),La(d)}}
async function Qa(a){var b=Na;if(!(ta||"function"!=typeof WebAssembly.instantiateStreaming||Ma(b)||qa(b)||fa)&&"function"==typeof fetch)try{var c=fetch(b,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(c,a)}catch(d){sa(`wasm streaming compile failed: ${d}`),sa("falling back to ArrayBuffer instantiation")}return Pa(b,a)}var y,C;class Ra{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}
var Sa=a=>{for(;0<a.length;)a.shift()(g)},Ua=g.noExitRuntime||!1,Va=[],Wa=0,D=0;function Xa(a,b,c){x[a.$a+16>>2]=0;x[a.$a+4>>2]=b;x[a.$a+8>>2]=c}class Ya{constructor(a){this.xb=a;this.$a=a-24}}
var ab=a=>{var b=D;if(!b)return Za(0),0;var c=new Ya(b);x[c.$a+16>>2]=b;var d=x[c.$a+4>>2];if(!d)return Za(0),b;for(var e of a){if(0===e||e===d)break;if($a(e,d,c.$a+16))return Za(e),b}Za(d);return b},E=()=>{var a=w[+bb>>2];bb+=4;return a},cb=(a,b)=>{for(var c=0,d=a.length-1;0<=d;d--){var e=a[d];"."===e?a.splice(d,1):".."===e?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a},db=a=>{var b="/"===a.charAt(0),c="/"===a.substr(-1);(a=cb(a.split("/").filter(d=>!!d),!b).join("/"))||
b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a},eb=a=>{var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&=b.substr(0,b.length-1);return a+b},fb=a=>{if("/"===a)return"/";a=db(a);a=a.replace(/\/$/,"");var b=a.lastIndexOf("/");return-1===b?a:a.substr(b+1)},gb=()=>{if("object"==typeof crypto&&"function"==typeof crypto.getRandomValues)return c=>crypto.getRandomValues(c);if(fa)try{var a=require("crypto");if(a.randomFillSync)return c=>
a.randomFillSync(c);var b=a.randomBytes;return c=>(c.set(b(c.byteLength)),c)}catch(c){}La("initRandomDevice")},hb=a=>(hb=gb())(a),ib=(...a)=>{for(var b="",c=!1,d=a.length-1;-1<=d&&!c;d--){c=0<=d?a[d]:"/";if("string"!=typeof c)throw new TypeError("Arguments to path.resolve must be strings");if(!c)return"";b=c+"/"+b;c="/"===c.charAt(0)}b=cb(b.split("/").filter(e=>!!e),!c).join("/");return(c?"/":"")+b||"."},jb=(a,b)=>{function c(h){for(var k=0;k<h.length&&""===h[k];k++);for(var p=h.length-1;0<=p&&""===
h[p];p--);return k>p?[]:h.slice(k,p-k+1)}a=ib(a).substr(1);b=ib(b).substr(1);a=c(a.split("/"));b=c(b.split("/"));for(var d=Math.min(a.length,b.length),e=d,f=0;f<d;f++)if(a[f]!==b[f]){e=f;break}d=[];for(f=e;f<a.length;f++)d.push("..");d=d.concat(b.slice(e));return d.join("/")},kb="undefined"!=typeof TextDecoder?new TextDecoder:void 0,F=(a,b=0)=>{for(var c=b+NaN,d=b;a[d]&&!(d>=c);)++d;if(16<d-b&&a.buffer&&kb)return kb.decode(a.subarray(b,d));for(c="";b<d;){var e=a[b++];if(e&128){var f=a[b++]&63;if(192==
(e&224))c+=String.fromCharCode((e&31)<<6|f);else{var h=a[b++]&63;e=224==(e&240)?(e&15)<<12|f<<6|h:(e&7)<<18|f<<12|h<<6|a[b++]&63;65536>e?c+=String.fromCharCode(e):(e-=65536,c+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else c+=String.fromCharCode(e)}return c},lb=[],mb=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b},nb=(a,b,c,d)=>{if(!(0<d))return 0;var e=c;d=c+d-1;for(var f=0;f<a.length;++f){var h=a.charCodeAt(f);
if(55296<=h&&57343>=h){var k=a.charCodeAt(++f);h=65536+((h&1023)<<10)|k&1023}if(127>=h){if(c>=d)break;b[c++]=h}else{if(2047>=h){if(c+1>=d)break;b[c++]=192|h>>6}else{if(65535>=h){if(c+2>=d)break;b[c++]=224|h>>12}else{if(c+3>=d)break;b[c++]=240|h>>18;b[c++]=128|h>>12&63}b[c++]=128|h>>6&63}b[c++]=128|h&63}}b[c]=0;return c-e};function ob(a){var b=Array(mb(a)+1);a=nb(a,b,0,b.length);b.length=a;return b}var pb=[];function qb(a,b){pb[a]={input:[],output:[],gb:b};rb(a,sb)}
var sb={open(a){var b=pb[a.node.rdev];if(!b)throw new G(43);a.tty=b;a.seekable=!1},close(a){a.tty.gb.fsync(a.tty)},fsync(a){a.tty.gb.fsync(a.tty)},read(a,b,c,d){if(!a.tty||!a.tty.gb.yb)throw new G(60);for(var e=0,f=0;f<d;f++){try{var h=a.tty.gb.yb(a.tty)}catch(k){throw new G(29);}if(void 0===h&&0===e)throw new G(6);if(null===h||void 0===h)break;e++;b[c+f]=h}e&&(a.node.atime=Date.now());return e},write(a,b,c,d){if(!a.tty||!a.tty.gb.qb)throw new G(60);try{for(var e=0;e<d;e++)a.tty.gb.qb(a.tty,b[c+e])}catch(f){throw new G(29);
}d&&(a.node.mtime=a.node.ctime=Date.now());return e}},ub={yb(){a:{if(!lb.length){var a=null;if(fa){var b=Buffer.alloc(256),c=0,d=process.stdin.fd;try{c=fs.readSync(d,b,0,256)}catch(e){if(e.toString().includes("EOF"))c=0;else throw e;}0<c&&(a=b.slice(0,c).toString("utf-8"))}else"undefined"!=typeof window&&"function"==typeof window.prompt&&(a=window.prompt("Input: "),null!==a&&(a+="\n"));if(!a){a=null;break a}lb=ob(a)}a=lb.shift()}return a},qb(a,b){null===b||10===b?(ra(F(a.output)),a.output=[]):0!=
b&&a.output.push(b)},fsync(a){a.output&&0<a.output.length&&(ra(F(a.output)),a.output=[])},Fb(){return{Qb:25856,Sb:5,Pb:191,Rb:35387,Ob:[3,28,127,21,4,0,1,0,17,19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]}},Gb(){return 0},Hb(){return[24,80]}},vb={qb(a,b){null===b||10===b?(sa(F(a.output)),a.output=[]):0!=b&&a.output.push(b)},fsync(a){a.output&&0<a.output.length&&(sa(F(a.output)),a.output=[])}};
function wb(a,b){var c=a.Va?a.Va.length:0;c>=b||(b=Math.max(b,c*(1048576>c?2:1.125)>>>0),0!=c&&(b=Math.max(b,256)),c=a.Va,a.Va=new Uint8Array(b),0<a.Xa&&a.Va.set(c.subarray(0,a.Xa),0))}
var I={fb:null,bb(){return I.createNode(null,"/",16895,0)},createNode(a,b,c,d){if(24576===(c&61440)||4096===(c&61440))throw new G(63);I.fb||(I.fb={dir:{node:{cb:I.Ua.cb,ab:I.Ua.ab,lookup:I.Ua.lookup,mb:I.Ua.mb,rename:I.Ua.rename,unlink:I.Ua.unlink,rmdir:I.Ua.rmdir,readdir:I.Ua.readdir,symlink:I.Ua.symlink},stream:{eb:I.Wa.eb}},file:{node:{cb:I.Ua.cb,ab:I.Ua.ab},stream:{eb:I.Wa.eb,read:I.Wa.read,write:I.Wa.write,ub:I.Wa.ub,pb:I.Wa.pb,Bb:I.Wa.Bb}},link:{node:{cb:I.Ua.cb,ab:I.Ua.ab,readlink:I.Ua.readlink},
stream:{}},vb:{node:{cb:I.Ua.cb,ab:I.Ua.ab},stream:xb}});c=yb(a,b,c,d);J(c.mode)?(c.Ua=I.fb.dir.node,c.Wa=I.fb.dir.stream,c.Va={}):32768===(c.mode&61440)?(c.Ua=I.fb.file.node,c.Wa=I.fb.file.stream,c.Xa=0,c.Va=null):40960===(c.mode&61440)?(c.Ua=I.fb.link.node,c.Wa=I.fb.link.stream):8192===(c.mode&61440)&&(c.Ua=I.fb.vb.node,c.Wa=I.fb.vb.stream);c.atime=c.mtime=c.ctime=Date.now();a&&(a.Va[b]=c,a.atime=a.mtime=a.ctime=c.atime);return c},Vb(a){return a.Va?a.Va.subarray?a.Va.subarray(0,a.Xa):new Uint8Array(a.Va):
new Uint8Array(0)},Ua:{cb(a){var b={};b.dev=8192===(a.mode&61440)?a.id:1;b.ino=a.id;b.mode=a.mode;b.nlink=1;b.uid=0;b.gid=0;b.rdev=a.rdev;J(a.mode)?b.size=4096:32768===(a.mode&61440)?b.size=a.Xa:40960===(a.mode&61440)?b.size=a.link.length:b.size=0;b.atime=new Date(a.atime);b.mtime=new Date(a.mtime);b.ctime=new Date(a.ctime);b.Db=4096;b.blocks=Math.ceil(b.size/b.Db);return b},ab(a,b){for(var c of["mode","atime","mtime","ctime"])b[c]&&(a[c]=b[c]);void 0!==b.size&&(b=b.size,a.Xa!=b&&(0==b?(a.Va=null,
a.Xa=0):(c=a.Va,a.Va=new Uint8Array(b),c&&a.Va.set(c.subarray(0,Math.min(b,a.Xa))),a.Xa=b)))},lookup(){throw I.wb;},mb(a,b,c,d){return I.createNode(a,b,c,d)},rename(a,b,c){try{var d=L(b,c)}catch(f){}if(d){if(J(a.mode))for(var e in d.Va)throw new G(55);zb(d)}delete a.parent.Va[a.name];b.Va[c]=a;a.name=c;b.ctime=b.mtime=a.parent.ctime=a.parent.mtime=Date.now()},unlink(a,b){delete a.Va[b];a.ctime=a.mtime=Date.now()},rmdir(a,b){var c=L(a,b),d;for(d in c.Va)throw new G(55);delete a.Va[b];a.ctime=a.mtime=
Date.now()},readdir(a){return[".","..",...Object.keys(a.Va)]},symlink(a,b,c){a=I.createNode(a,b,41471,0);a.link=c;return a},readlink(a){if(40960!==(a.mode&61440))throw new G(28);return a.link}},Wa:{read(a,b,c,d,e){var f=a.node.Va;if(e>=a.node.Xa)return 0;a=Math.min(a.node.Xa-e,d);if(8<a&&f.subarray)b.set(f.subarray(e,e+a),c);else for(d=0;d<a;d++)b[c+d]=f[e+d];return a},write(a,b,c,d,e,f){b.buffer===u.buffer&&(f=!1);if(!d)return 0;a=a.node;a.mtime=a.ctime=Date.now();if(b.subarray&&(!a.Va||a.Va.subarray)){if(f)return a.Va=
b.subarray(c,c+d),a.Xa=d;if(0===a.Xa&&0===e)return a.Va=b.slice(c,c+d),a.Xa=d;if(e+d<=a.Xa)return a.Va.set(b.subarray(c,c+d),e),d}wb(a,e+d);if(a.Va.subarray&&b.subarray)a.Va.set(b.subarray(c,c+d),e);else for(f=0;f<d;f++)a.Va[e+f]=b[c+f];a.Xa=Math.max(a.Xa,e+d);return d},eb(a,b,c){1===c?b+=a.position:2===c&&32768===(a.node.mode&61440)&&(b+=a.node.Xa);if(0>b)throw new G(28);return b},ub(a,b,c){wb(a.node,b+c);a.node.Xa=Math.max(a.node.Xa,b+c)},pb(a,b,c,d,e){if(32768!==(a.node.mode&61440))throw new G(43);
a=a.node.Va;if(e&2||!a||a.buffer!==u.buffer){d=!0;La();e=void 0;if(!e)throw new G(48);if(a){if(0<c||c+b<a.length)a.subarray?a=a.subarray(c,c+b):a=Array.prototype.slice.call(a,c,c+b);u.set(a,e)}}else d=!1,e=a.byteOffset;return{$a:e,Nb:d}},Bb(a,b,c,d){I.Wa.write(a,b,0,d,c,!1);return 0}}},Ab=async a=>{a=await oa(a);return new Uint8Array(a)},Bb=g.preloadPlugins||[],Cb=(a,b,c,d)=>{"undefined"!=typeof Browser&&Xa(Browser);var e=!1;Bb.forEach(f=>{!e&&f.canHandle(b)&&(f.handle(a,b,c,d),e=!0)});return e},
Eb=(a,b,c,d,e,f,h,k,p,n)=>{function l(B){function t(r){n?.();k||Db(a,b,r,d,e,p);f?.();Ka(z)}Cb(B,q,t,()=>{h?.();Ka(z)})||t(B)}var q=b?ib(db(a+"/"+b)):a,z=`cp ${q}`;Ja(z);"string"==typeof c?Ab(c).then(l,h):l(c)},Fb=(a,b)=>{var c=0;a&&(c|=365);b&&(c|=146);return c},Gb=null,Hb={},N=[],Ib=1,O=null,Jb=!1,Kb=!0,G=class{name="ErrnoError";constructor(a){this.Ya=a}},Lb={},Mb=class{Za={};node=null;get flags(){return this.Za.flags}set flags(a){this.Za.flags=a}get position(){return this.Za.position}set position(a){this.Za.position=
a}},Nb=class{Ua={};Wa={};hb=null;constructor(a,b,c,d){a||=this;this.parent=a;this.bb=a.bb;this.id=Ib++;this.name=b;this.mode=c;this.rdev=d;this.atime=this.mtime=this.ctime=Date.now()}get read(){return 365===(this.mode&365)}set read(a){a?this.mode|=365:this.mode&=-366}get write(){return 146===(this.mode&146)}set write(a){a?this.mode|=146:this.mode&=-147}get Jb(){return J(this.mode)}get Ib(){return 8192===(this.mode&61440)}};
function P(a,b={}){if(!a)return{path:"",node:null};b.nb??(b.nb=!0);"/"===a.charAt(0)||(a="//"+a);var c=0;a:for(;40>c;c++){a=a.split("/").filter(k=>!!k&&"."!==k);for(var d=Gb,e="/",f=0;f<a.length;f++){var h=f===a.length-1;if(h&&b.parent)break;if(".."===a[f])e=eb(e),d=d.parent;else{e=db(e+"/"+a[f]);try{d=L(d,a[f])}catch(k){if(44===k?.Ya&&h&&b.Lb)return{path:e};throw k;}!d.hb||h&&!b.nb||(d=d.hb.root);if(40960===(d.mode&61440)&&(!h||b.lb)){if(!d.Ua.readlink)throw new G(52);d=d.Ua.readlink(d);"/"===d.charAt(0)||
(d=eb(e)+"/"+d);a=d+"/"+a.slice(f+1).join("/");continue a}}}return{path:e,node:d}}throw new G(32);}function Ob(a){for(var b;;){if(a===a.parent)return a=a.bb.Ab,b?"/"!==a[a.length-1]?`${a}/${b}`:a+b:a;b=b?`${a.name}/${b}`:a.name;a=a.parent}}function Pb(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%O.length}function Qb(a){var b=Pb(a.parent.id,a.name);a.ib=O[b];O[b]=a}
function zb(a){var b=Pb(a.parent.id,a.name);if(O[b]===a)O[b]=a.ib;else for(b=O[b];b;){if(b.ib===a){b.ib=a.ib;break}b=b.ib}}function L(a,b){var c=J(a.mode)?(c=Rb(a,"x"))?c:a.Ua.lookup?0:2:54;if(c)throw new G(c);for(c=O[Pb(a.id,b)];c;c=c.ib){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.Ua.lookup(a,b)}function yb(a,b,c,d){a=new Nb(a,b,c,d);Qb(a);return a}function J(a){return 16384===(a&61440)}function Sb(a){var b=["r","w","rw"][a&3];a&512&&(b+="w");return b}
function Rb(a,b){if(Kb)return 0;if(!b.includes("r")||a.mode&292){if(b.includes("w")&&!(a.mode&146)||b.includes("x")&&!(a.mode&73))return 2}else return 2;return 0}function Tb(a,b){if(!J(a.mode))return 54;try{return L(a,b),20}catch(c){}return Rb(a,"wx")}function Ub(a,b,c){try{var d=L(a,b)}catch(e){return e.Ya}if(a=Rb(a,"wx"))return a;if(c){if(!J(d.mode))return 54;if(d===d.parent||"/"===Ob(d))return 10}else if(J(d.mode))return 31;return 0}function Q(a){a=N[a];if(!a)throw new G(8);return a}
function Vb(a,b=-1){a=Object.assign(new Mb,a);if(-1==b)a:{for(b=0;4096>=b;b++)if(!N[b])break a;throw new G(33);}a.fd=b;return N[b]=a}function Wb(a,b=-1){a=Vb(a,b);a.Wa?.Tb?.(a);return a}var xb={open(a){a.Wa=Hb[a.node.rdev].Wa;a.Wa.open?.(a)},eb(){throw new G(70);}};function rb(a,b){Hb[a]={Wa:b}}
function Xb(a,b){var c="/"===b;if(c&&Gb)throw new G(10);if(!c&&b){var d=P(b,{nb:!1});b=d.path;d=d.node;if(d.hb)throw new G(10);if(!J(d.mode))throw new G(54);}b={type:a,Wb:{},Ab:b,Kb:[]};a=a.bb(b);a.bb=b;b.root=a;c?Gb=a:d&&(d.hb=b,d.bb&&d.bb.Kb.push(b))}function Yb(a,b,c){var d=P(a,{parent:!0}).node;a=fb(a);if(!a||"."===a||".."===a)throw new G(28);var e=Tb(d,a);if(e)throw new G(e);if(!d.Ua.mb)throw new G(63);return d.Ua.mb(d,a,b,c)}function Zb(a,b=438){return Yb(a,b&4095|32768,0)}
function S(a){return Yb(a,16895,0)}function $b(a,b,c){"undefined"==typeof c&&(c=b,b=438);return Yb(a,b|8192,c)}function ac(a,b){if(!ib(a))throw new G(44);var c=P(b,{parent:!0}).node;if(!c)throw new G(44);b=fb(b);var d=Tb(c,b);if(d)throw new G(d);if(!c.Ua.symlink)throw new G(63);c.Ua.symlink(c,b,a)}function bc(a){var b=P(a,{parent:!0}).node;a=fb(a);var c=L(b,a),d=Ub(b,a,!0);if(d)throw new G(d);if(!b.Ua.rmdir)throw new G(63);if(c.hb)throw new G(10);b.Ua.rmdir(b,a);zb(c)}
function cc(a){var b=P(a,{parent:!0}).node;if(!b)throw new G(44);a=fb(a);var c=L(b,a),d=Ub(b,a,!1);if(d)throw new G(d);if(!b.Ua.unlink)throw new G(63);if(c.hb)throw new G(10);b.Ua.unlink(b,a);zb(c)}function dc(a,b){a="string"==typeof a?P(a,{lb:!0}).node:a;if(!a.Ua.ab)throw new G(63);a.Ua.ab(a,{mode:b&4095|a.mode&-4096,ctime:Date.now()})}
function ec(a,b,c=438){if(""===a)throw new G(44);if("string"==typeof b){var d={r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090}[b];if("undefined"==typeof d)throw Error(`Unknown file open mode: ${b}`);b=d}c=b&64?c&4095|32768:0;"object"==typeof a?d=a:(a=P(a,{lb:!(b&131072),Lb:!0}),d=a.node,a=a.path);var e=!1;if(b&64)if(d){if(b&128)throw new G(20);}else d=Yb(a,c,0),e=!0;if(!d)throw new G(44);8192===(d.mode&61440)&&(b&=-513);if(b&65536&&!J(d.mode))throw new G(54);if(!e&&(c=d?40960===(d.mode&61440)?32:J(d.mode)&&
("r"!==Sb(b)||b&512)?31:Rb(d,Sb(b)):44))throw new G(c);if(b&512&&!e){c=d;c="string"==typeof c?P(c,{lb:!0}).node:c;if(!c.Ua.ab)throw new G(63);if(J(c.mode))throw new G(31);if(32768!==(c.mode&61440))throw new G(28);if(e=Rb(c,"w"))throw new G(e);c.Ua.ab(c,{size:0,timestamp:Date.now()})}b&=-131713;d=Vb({node:d,path:Ob(d),flags:b,seekable:!0,position:0,Wa:d.Wa,Mb:[],error:!1});d.Wa.open&&d.Wa.open(d);!g.logReadFiles||b&1||a in Lb||(Lb[a]=1);return d}
function fc(a){if(null===a.fd)throw new G(8);a.ob&&(a.ob=null);try{a.Wa.close&&a.Wa.close(a)}catch(b){throw b;}finally{N[a.fd]=null}a.fd=null}function gc(a,b,c){if(null===a.fd)throw new G(8);if(!a.seekable||!a.Wa.eb)throw new G(70);if(0!=c&&1!=c&&2!=c)throw new G(28);a.position=a.Wa.eb(a,b,c);a.Mb=[]}
function hc(a,b,c,d,e,f){if(0>d||0>e)throw new G(28);if(null===a.fd)throw new G(8);if(0===(a.flags&2097155))throw new G(8);if(J(a.node.mode))throw new G(31);if(!a.Wa.write)throw new G(28);a.seekable&&a.flags&1024&&gc(a,0,2);var h="undefined"!=typeof e;if(!h)e=a.position;else if(!a.seekable)throw new G(70);b=a.Wa.write(a,b,c,d,e,f);h||(a.position+=b);return b}
function ha(a,b,c){Jb=!0;a??=g.stdin;b??=g.stdout;c??=g.stderr;a?T("/dev","stdin",a):ac("/dev/tty","/dev/stdin");b?T("/dev","stdout",null,b):ac("/dev/tty","/dev/stdout");c?T("/dev","stderr",null,c):ac("/dev/tty1","/dev/stderr");ec("/dev/stdin",0);ec("/dev/stdout",1);ec("/dev/stderr",1)}function ic(a,b){a="string"==typeof a?a:Ob(a);for(b=b.split("/").reverse();b.length;){var c=b.pop();if(c){var d=db(a+"/"+c);try{S(d)}catch(e){}a=d}}return d}
function jc(a,b,c,d){a=db(("string"==typeof a?a:Ob(a))+"/"+b);return Zb(a,Fb(c,d))}function Db(a,b,c,d,e,f){var h=b;a&&(a="string"==typeof a?a:Ob(a),h=b?db(a+"/"+b):a);a=Fb(d,e);h=Zb(h,a);if(c){if("string"==typeof c){b=Array(c.length);d=0;for(e=c.length;d<e;++d)b[d]=c.charCodeAt(d);c=b}dc(h,a|146);b=ec(h,577);hc(b,c,0,c.length,0,f);fc(b);dc(h,a)}}
function T(a,b,c,d){a=db(("string"==typeof a?a:Ob(a))+"/"+b);b=Fb(!!c,!!d);T.zb??(T.zb=64);var e=T.zb++<<8|0;rb(e,{open(f){f.seekable=!1},close(){d?.buffer?.length&&d(10)},read(f,h,k,p){for(var n=0,l=0;l<p;l++){try{var q=c()}catch(z){throw new G(29);}if(void 0===q&&0===n)throw new G(6);if(null===q||void 0===q)break;n++;h[k+l]=q}n&&(f.node.atime=Date.now());return n},write(f,h,k,p){for(var n=0;n<p;n++)try{d(h[k+n])}catch(l){throw new G(29);}p&&(f.node.mtime=f.node.ctime=Date.now());return n}});return $b(a,
b,e)}function kc(a){if(!(a.Ib||a.Jb||a.link||a.Va)){if("undefined"!=typeof XMLHttpRequest)throw Error("Lazy loading should have been performed (contents set) in createLazyFile, but it was not. Lazy loading only works in web workers. Use --embed-file or --preload-file in emcc on the main thread.");try{a.Va=pa(a.url),a.Xa=a.Va.length}catch(b){throw new G(29);}}}
function lc(a,b,c,d,e){class f{kb=!1;Za=[];jb=void 0;sb=0;rb=0;get(l){if(!(l>this.length-1||0>l)){var q=l%this.chunkSize;return this.jb(l/this.chunkSize|0)[q]}}Cb(l){this.jb=l}tb(){var l=new XMLHttpRequest;l.open("HEAD",c,!1);l.send(null);if(!(200<=l.status&&300>l.status||304===l.status))throw Error("Couldn't load "+c+". Status: "+l.status);var q=Number(l.getResponseHeader("Content-length")),z,B=(z=l.getResponseHeader("Accept-Ranges"))&&"bytes"===z;l=(z=l.getResponseHeader("Content-Encoding"))&&"gzip"===
z;var t=1048576;B||(t=q);var r=this;r.Cb(A=>{var H=A*t,M=(A+1)*t-1;M=Math.min(M,q-1);if("undefined"==typeof r.Za[A]){var ya=r.Za;if(H>M)throw Error("invalid range ("+H+", "+M+") or no bytes requested!");if(M>q-1)throw Error("only "+q+" bytes available! programmer error!");var K=new XMLHttpRequest;K.open("GET",c,!1);q!==t&&K.setRequestHeader("Range","bytes="+H+"-"+M);K.responseType="arraybuffer";K.overrideMimeType&&K.overrideMimeType("text/plain; charset=x-user-defined");K.send(null);if(!(200<=K.status&&
300>K.status||304===K.status))throw Error("Couldn't load "+c+". Status: "+K.status);H=void 0!==K.response?new Uint8Array(K.response||[]):ob(K.responseText||"");ya[A]=H}if("undefined"==typeof r.Za[A])throw Error("doXHR failed!");return r.Za[A]});if(l||!q)t=q=1,t=q=this.jb(0).length,ra("LazyFiles on gzip forces download of the whole file when length is accessed");this.sb=q;this.rb=t;this.kb=!0}get length(){this.kb||this.tb();return this.sb}get chunkSize(){this.kb||this.tb();return this.rb}}if("undefined"!=
typeof XMLHttpRequest){if(!ea)throw"Cannot do synchronous binary XHRs outside webworkers in modern browsers. Use --embed-file or --preload-file in emcc";var h=new f;var k=void 0}else k=c,h=void 0;var p=jc(a,b,d,e);h?p.Va=h:k&&(p.Va=null,p.url=k);Object.defineProperties(p,{Xa:{get:function(){return this.Va.length}}});var n={};Object.keys(p.Wa).forEach(l=>{var q=p.Wa[l];n[l]=(...z)=>{kc(p);return q(...z)}});n.read=(l,q,z,B,t)=>{kc(p);l=l.node.Va;if(t>=l.length)q=0;else{B=Math.min(l.length-t,B);if(l.slice)for(var r=
0;r<B;r++)q[z+r]=l[t+r];else for(r=0;r<B;r++)q[z+r]=l.get(t+r);q=B}return q};n.pb=()=>{kc(p);La();throw new G(48);};p.Wa=n;return p}var U={};function mc(a,b){if("/"===b.charAt(0))return b;a=-100===a?"/":Q(a).path;if(0==b.length)throw new G(44);return a+"/"+b}
var bb=void 0,nc=0,oc={},pc=a=>{a instanceof Ra||"unwind"==a||na(1,a)},qc=a=>{wa=a;Ua||0<nc||(g.onExit?.(a),va=!0);na(a,new Ra(a))},tc=a=>{wa=a;if(!(Ua||0<nc)){rc();Sa(Da);Jb=!1;sc(0);for(var b=0;b<N.length;b++){var c=N[b];c&&fc(c)}Fa=!0}qc(a)},uc=a=>{if(!Fa&&!va)try{if(a(),!(Fa||Ua||0<nc))try{tc(wa)}catch(b){pc(b)}}catch(b){pc(b)}},vc=a=>{Ua=!1;nc=0;tc(a)};g._emscripten_force_exit=vc;
var wc={},yc=()=>{if(!xc){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"==typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:ma||"./this.program"},b;for(b in wc)void 0===wc[b]?delete a[b]:a[b]=wc[b];var c=[];for(b in a)c.push(`${b}=${a[b]}`);xc=c}return xc},xc,Ac=a=>{var b=mb(a)+1,c=zc(b);nb(a,v,c,b);return c},Bc=[],Cc,V=a=>{var b=Bc[a];b||(a>=Bc.length&&(Bc.length=a+1),Bc[a]=b=Cc.get(a));return b},Ec=(a,
b,c,d)=>{var e={string:n=>{var l=0;null!==n&&void 0!==n&&0!==n&&(l=Ac(n));return l},array:n=>{var l=zc(n.length);u.set(n,l);return l}};a=g["_"+a];var f=[],h=0;if(d)for(var k=0;k<d.length;k++){var p=e[c[k]];p?(0===h&&(h=W()),f[k]=p(d[k])):f[k]=d[k]}c=a(...f);return c=function(n){0!==h&&X(h);return"string"===b?n?F(v,n):"":"boolean"===b?!!n:n}(c)};O=Array(4096);Xb(I,"/");S("/tmp");S("/home");S("/home/web_user");
(function(){S("/dev");rb(259,{read:()=>0,write:(d,e,f,h)=>h,eb:()=>0});$b("/dev/null",259);qb(1280,ub);qb(1536,vb);$b("/dev/tty",1280);$b("/dev/tty1",1536);var a=new Uint8Array(1024),b=0,c=()=>{0===b&&(b=hb(a).byteLength);return a[--b]};T("/dev","random",c);T("/dev","urandom",c);S("/dev/shm");S("/dev/shm/tmp")})();
(function(){S("/proc");var a=S("/proc/self");S("/proc/self/fd");Xb({bb(){var b=yb(a,"fd",16895,73);b.Wa={eb:I.Wa.eb};b.Ua={lookup(c,d){c=+d;var e=Q(c);c={parent:null,bb:{Ab:"fake"},Ua:{readlink:()=>e.path},id:c+1};return c.parent=c},readdir(){return Array.from(N.entries()).filter(([,c])=>c).map(([c])=>c.toString())}};return b}},"/proc/self/fd")})();g.FS_createPath=ic;g.FS_createDataFile=Db;g.FS_createPreloadedFile=Eb;g.FS_unlink=cc;g.FS_createLazyFile=lc;g.FS_createDevice=T;I.wb=new G(44);
I.wb.stack="<generic error, no stack>";
var ud={o:a=>{var b=new Ya(a);0==u[b.$a+12]&&(u[b.$a+12]=1,Wa--);u[b.$a+13]=0;Va.push(b);Fc(a);return Gc(a)},q:()=>{Y(0,0);var a=Va.pop();Hc(a.xb);D=0},b:()=>ab([]),f:a=>ab([a]),m:(a,b)=>ab([a,b]),G:()=>{var a=Va.pop();a||La("no exception to throw");var b=a.xb;0==u[a.$a+13]&&(Va.push(a),u[a.$a+13]=1,u[a.$a+12]=0,Wa++);D=b;throw D;},s:(a,b,c)=>{Xa(new Ya(a),b,c);D=a;Wa++;throw D;},qa:()=>Wa,g:a=>{D||=a;throw D;},I:function(a,b,c){bb=c;try{var d=Q(a);switch(b){case 0:var e=E();if(0>e)break;for(;N[e];)e++;
return Wb(d,e).fd;case 1:case 2:return 0;case 3:return d.flags;case 4:return e=E(),d.flags|=e,0;case 12:return e=E(),xa[e+0>>1]=2,0;case 13:case 14:return 0}return-28}catch(f){if("undefined"==typeof U||"ErrnoError"!==f.name)throw f;return-f.Ya}},L:function(a,b){try{if(0===b)return-28;var c=mb("/")+1;if(b<c)return-68;nb("/",v,a,b);return c}catch(d){if("undefined"==typeof U||"ErrnoError"!==d.name)throw d;return-d.Ya}},pa:function(a,b,c){bb=c;try{var d=Q(a);switch(b){case 21509:return d.tty?0:-59;case 21505:if(!d.tty)return-59;
if(d.tty.gb.Fb){a=[3,28,127,21,4,0,1,0,17,19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0];var e=E();w[e>>2]=25856;w[e+4>>2]=5;w[e+8>>2]=191;w[e+12>>2]=35387;for(var f=0;32>f;f++)u[e+f+17]=a[f]||0}return 0;case 21510:case 21511:case 21512:return d.tty?0:-59;case 21506:case 21507:case 21508:if(!d.tty)return-59;if(d.tty.gb.Gb)for(e=E(),a=[],f=0;32>f;f++)a.push(u[e+f+17]);return 0;case 21519:if(!d.tty)return-59;e=E();return w[e>>2]=0;case 21520:return d.tty?-28:-59;case 21531:e=E();if(!d.Wa.Eb)throw new G(59);
return d.Wa.Eb(d,b,e);case 21523:if(!d.tty)return-59;d.tty.gb.Hb&&(f=[24,80],e=E(),xa[e>>1]=f[0],xa[e+2>>1]=f[1]);return 0;case 21524:return d.tty?0:-59;case 21515:return d.tty?0:-59;default:return-28}}catch(h){if("undefined"==typeof U||"ErrnoError"!==h.name)throw h;return-h.Ya}},ra:function(a,b,c,d){bb=d;try{b=b?F(v,b):"";b=mc(a,b);var e=d?E():0;return ec(b,c,e).fd}catch(f){if("undefined"==typeof U||"ErrnoError"!==f.name)throw f;return-f.Ya}},ga:function(a,b,c,d){try{b=b?F(v,b):"";d=d?F(v,d):"";
b=mc(a,b);d=mc(c,d);a=b;var e=eb(a),f=eb(d),h=fb(a),k=fb(d);var p=P(a,{parent:!0});var n=p.node;p=P(d,{parent:!0});var l=p.node;if(!n||!l)throw new G(44);if(n.bb!==l.bb)throw new G(75);var q=L(n,h),z=jb(a,f);if("."!==z.charAt(0))throw new G(28);z=jb(d,e);if("."!==z.charAt(0))throw new G(55);try{var B=L(l,k)}catch(A){}if(q!==B){var t=J(q.mode),r=Ub(n,h,t);if(r)throw new G(r);if(r=B?Ub(l,k,t):Tb(l,k))throw new G(r);if(!n.Ua.rename)throw new G(63);if(q.hb||B&&B.hb)throw new G(10);if(l!==n&&(r=Rb(n,"w")))throw new G(r);
zb(q);try{n.Ua.rename(q,l,k),q.parent=l}catch(A){throw A;}finally{Qb(q)}}return 0}catch(A){if("undefined"==typeof U||"ErrnoError"!==A.name)throw A;return-A.Ya}},ha:function(a){try{return a=a?F(v,a):"",bc(a),0}catch(b){if("undefined"==typeof U||"ErrnoError"!==b.name)throw b;return-b.Ya}},ja:function(a,b){try{a=a?F(v,a):"";var c=P(a,{lb:!0}).node;if(!c)throw new G(44);if(!c.Ua.cb)throw new G(63);var d=c.Ua.cb(c);w[b>>2]=d.dev;w[b+4>>2]=d.mode;x[b+8>>2]=d.nlink;w[b+12>>2]=d.uid;w[b+16>>2]=d.gid;w[b+
20>>2]=d.rdev;C=[d.size>>>0,(y=d.size,1<=+Math.abs(y)?0<y?+Math.floor(y/4294967296)>>>0:~~+Math.ceil((y-+(~~y>>>0))/4294967296)>>>0:0)];w[b+24>>2]=C[0];w[b+28>>2]=C[1];w[b+32>>2]=4096;w[b+36>>2]=d.blocks;var e=d.atime.getTime(),f=d.mtime.getTime(),h=d.ctime.getTime();C=[Math.floor(e/1E3)>>>0,(y=Math.floor(e/1E3),1<=+Math.abs(y)?0<y?+Math.floor(y/4294967296)>>>0:~~+Math.ceil((y-+(~~y>>>0))/4294967296)>>>0:0)];w[b+40>>2]=C[0];w[b+44>>2]=C[1];x[b+48>>2]=e%1E3*1E6;C=[Math.floor(f/1E3)>>>0,(y=Math.floor(f/
1E3),1<=+Math.abs(y)?0<y?+Math.floor(y/4294967296)>>>0:~~+Math.ceil((y-+(~~y>>>0))/4294967296)>>>0:0)];w[b+56>>2]=C[0];w[b+60>>2]=C[1];x[b+64>>2]=f%1E3*1E6;C=[Math.floor(h/1E3)>>>0,(y=Math.floor(h/1E3),1<=+Math.abs(y)?0<y?+Math.floor(y/4294967296)>>>0:~~+Math.ceil((y-+(~~y>>>0))/4294967296)>>>0:0)];w[b+72>>2]=C[0];w[b+76>>2]=C[1];x[b+80>>2]=h%1E3*1E6;C=[d.ino>>>0,(y=d.ino,1<=+Math.abs(y)?0<y?+Math.floor(y/4294967296)>>>0:~~+Math.ceil((y-+(~~y>>>0))/4294967296)>>>0:0)];w[b+88>>2]=C[0];w[b+92>>2]=C[1];
return 0}catch(k){if("undefined"==typeof U||"ErrnoError"!==k.name)throw k;return-k.Ya}},ia:function(a,b,c){try{return b=b?F(v,b):"",b=mc(a,b),0===c?cc(b):512===c?bc(b):La("Invalid flags passed to unlinkat"),0}catch(d){if("undefined"==typeof U||"ErrnoError"!==d.name)throw d;return-d.Ya}},fa:()=>La(""),V:(a,b,c)=>v.copyWithin(a,b,b+c),da:()=>{Ua=!1;nc=0},ea:(a,b)=>{oc[a]&&(clearTimeout(oc[a].id),delete oc[a]);if(!b)return 0;var c=setTimeout(()=>{delete oc[a];uc(()=>Ic(a,performance.now()))},b);oc[a]=
{id:c,Xb:b};return 0},ka:(a,b,c,d)=>{var e=(new Date).getFullYear(),f=(new Date(e,0,1)).getTimezoneOffset();e=(new Date(e,6,1)).getTimezoneOffset();x[a>>2]=60*Math.max(f,e);w[b>>2]=Number(f!=e);b=h=>{var k=Math.abs(h);return`UTC${0<=h?"-":"+"}${String(Math.floor(k/60)).padStart(2,"0")}${String(k%60).padStart(2,"0")}`};a=b(f);b=b(e);e<f?(nb(a,v,c,17),nb(b,v,d,17)):(nb(a,v,d,17),nb(b,v,c,17))},Y:function(a,b,c,d){if(!(0<=a&&3>=a))return 28;a=Math.round(1E6*(0===a?Date.now():performance.now()));C=[a>>>
0,(y=a,1<=+Math.abs(y)?0<y?+Math.floor(y/4294967296)>>>0:~~+Math.ceil((y-+(~~y>>>0))/4294967296)>>>0:0)];w[d>>2]=C[0];w[d+4>>2]=C[1];return 0},ba:vc,J:a=>{var b=v.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);a:{d=(Math.min(2147483648,65536*Math.ceil(Math.max(a,d)/65536))-ua.buffer.byteLength+65535)/65536|0;try{ua.grow(d);za();var e=1;break a}catch(f){}e=void 0}if(e)return!0}return!1},la:(a,b)=>{var c=0;yc().forEach((d,e)=>{var f=b+c;e=x[a+
4*e>>2]=f;for(f=0;f<d.length;++f)u[e++]=d.charCodeAt(f);u[e]=0;c+=d.length+1});return 0},ma:(a,b)=>{var c=yc();x[a>>2]=c.length;var d=0;c.forEach(e=>d+=e.length+1);x[b>>2]=d;return 0},aa:tc,E:function(a){try{var b=Q(a);fc(b);return 0}catch(c){if("undefined"==typeof U||"ErrnoError"!==c.name)throw c;return c.Ya}},oa:function(a,b,c,d){try{a:{var e=Q(a);a=b;for(var f,h=b=0;h<c;h++){var k=x[a>>2],p=x[a+4>>2];a+=8;var n=e,l=k,q=p,z=f,B=u;if(0>q||0>z)throw new G(28);if(null===n.fd)throw new G(8);if(1===
(n.flags&2097155))throw new G(8);if(J(n.node.mode))throw new G(31);if(!n.Wa.read)throw new G(28);var t="undefined"!=typeof z;if(!t)z=n.position;else if(!n.seekable)throw new G(70);var r=n.Wa.read(n,B,l,q,z);t||(n.position+=r);var A=r;if(0>A){var H=-1;break a}b+=A;if(A<p)break;"undefined"!=typeof f&&(f+=A)}H=b}x[d>>2]=H;return 0}catch(M){if("undefined"==typeof U||"ErrnoError"!==M.name)throw M;return M.Ya}},X:function(a,b,c,d,e){b=c+2097152>>>0<4194305-!!b?(b>>>0)+4294967296*c:NaN;try{if(isNaN(b))return 61;
var f=Q(a);gc(f,b,d);C=[f.position>>>0,(y=f.position,1<=+Math.abs(y)?0<y?+Math.floor(y/4294967296)>>>0:~~+Math.ceil((y-+(~~y>>>0))/4294967296)>>>0:0)];w[e>>2]=C[0];w[e+4>>2]=C[1];f.ob&&0===b&&0===d&&(f.ob=null);return 0}catch(h){if("undefined"==typeof U||"ErrnoError"!==h.name)throw h;return h.Ya}},na:function(a,b,c,d){try{a:{var e=Q(a);a=b;for(var f,h=b=0;h<c;h++){var k=x[a>>2],p=x[a+4>>2];a+=8;var n=hc(e,u,k,p,f);if(0>n){var l=-1;break a}b+=n;if(n<p)break;"undefined"!=typeof f&&(f+=n)}l=b}x[d>>2]=
l;return 0}catch(q){if("undefined"==typeof U||"ErrnoError"!==q.name)throw q;return q.Ya}},$:Jc,Z:Kc,H:Lc,e:Mc,w:Nc,c:Oc,d:Pc,t:Qc,_:Rc,r:Sc,p:Tc,x:Uc,y:Vc,F:Wc,D:Xc,M:Yc,N:Zc,O:$c,W:ad,P:bd,U:cd,Q:dd,K:ed,i:fd,l:gd,h:hd,j:jd,k:kd,n:ld,B:md,v:nd,A:od,C:pd,z:qd,R:rd,T:sd,S:td,u:a=>a,a:ua,ca:qc},Z;
(async function(){function a(d){Z=d.exports;Cc=Z.va;Ba.unshift(Z.sa);Ka("wasm-instantiate");return Z}Ja("wasm-instantiate");var b={a:ud};if(g.instantiateWasm)try{return g.instantiateWasm(b,a)}catch(d){sa(`Module.instantiateWasm callback failed with error: ${d}`),ba(d)}Na??=Ma("rapfi-single.wasm")?"rapfi-single.wasm":g.locateFile?g.locateFile("rapfi-single.wasm",m):m+"rapfi-single.wasm";try{var c=await Qa(b);a(c.instance);return c}catch(d){ba(d)}})();g._gomocupLoopOnce=()=>(g._gomocupLoopOnce=Z.ta)();
var vd=g._main=(a,b)=>(vd=g._main=Z.ua)(a,b),rc=()=>(rc=Z.wa)(),sc=a=>(sc=Z.xa)(a),Ic=(a,b)=>(Ic=Z.ya)(a,b),Y=(a,b)=>(Y=Z.za)(a,b),Za=a=>(Za=Z.Aa)(a),X=a=>(X=Z.Ba)(a),zc=a=>(zc=Z.Ca)(a),W=()=>(W=Z.Da)(),Hc=a=>(Hc=Z.Ea)(a),Fc=a=>(Fc=Z.Fa)(a),$a=(a,b,c)=>($a=Z.Ga)(a,b,c),Gc=a=>(Gc=Z.Ha)(a),wd=g.dynCall_iij=(a,b,c,d)=>(wd=g.dynCall_iij=Z.Ia)(a,b,c,d),xd=g.dynCall_ji=(a,b)=>(xd=g.dynCall_ji=Z.Ja)(a,b),yd=g.dynCall_j=a=>(yd=g.dynCall_j=Z.Ka)(a),zd=g.dynCall_iiiiij=(a,b,c,d,e,f,h)=>(zd=g.dynCall_iiiiij=
Z.La)(a,b,c,d,e,f,h),Ad=g.dynCall_viiij=(a,b,c,d,e,f)=>(Ad=g.dynCall_viiij=Z.Ma)(a,b,c,d,e,f),Bd=g.dynCall_viijj=(a,b,c,d,e,f,h)=>(Bd=g.dynCall_viijj=Z.Na)(a,b,c,d,e,f,h),Cd=g.dynCall_vij=(a,b,c,d)=>(Cd=g.dynCall_vij=Z.Oa)(a,b,c,d),Dd=g.dynCall_viiji=(a,b,c,d,e,f)=>(Dd=g.dynCall_viiji=Z.Pa)(a,b,c,d,e,f),Ed=g.dynCall_jii=(a,b,c)=>(Ed=g.dynCall_jii=Z.Qa)(a,b,c),Fd=g.dynCall_jiii=(a,b,c,d)=>(Fd=g.dynCall_jiii=Z.Ra)(a,b,c,d),Gd=g.dynCall_iiij=(a,b,c,d,e)=>(Gd=g.dynCall_iiij=Z.Sa)(a,b,c,d,e),Hd=g.dynCall_iiiij=
(a,b,c,d,e,f)=>(Hd=g.dynCall_iiiij=Z.Ta)(a,b,c,d,e,f);function Oc(a,b,c){var d=W();try{return V(a)(b,c)}catch(e){X(d);if(e!==e+0)throw e;Y(1,0)}}function Pc(a,b,c,d){var e=W();try{return V(a)(b,c,d)}catch(f){X(e);if(f!==f+0)throw f;Y(1,0)}}function jd(a,b,c,d){var e=W();try{V(a)(b,c,d)}catch(f){X(e);if(f!==f+0)throw f;Y(1,0)}}function hd(a,b,c){var d=W();try{V(a)(b,c)}catch(e){X(d);if(e!==e+0)throw e;Y(1,0)}}function fd(a){var b=W();try{V(a)()}catch(c){X(b);if(c!==c+0)throw c;Y(1,0)}}
function Mc(a,b){var c=W();try{return V(a)(b)}catch(d){X(c);if(d!==d+0)throw d;Y(1,0)}}function Vc(a,b,c,d,e,f,h){var k=W();try{return V(a)(b,c,d,e,f,h)}catch(p){X(k);if(p!==p+0)throw p;Y(1,0)}}function gd(a,b){var c=W();try{V(a)(b)}catch(d){X(c);if(d!==d+0)throw d;Y(1,0)}}function kd(a,b,c,d,e){var f=W();try{V(a)(b,c,d,e)}catch(h){X(f);if(h!==h+0)throw h;Y(1,0)}}function Lc(a){var b=W();try{return V(a)()}catch(c){X(b);if(c!==c+0)throw c;Y(1,0)}}
function Uc(a,b,c,d,e,f){var h=W();try{return V(a)(b,c,d,e,f)}catch(k){X(h);if(k!==k+0)throw k;Y(1,0)}}function Qc(a,b,c,d,e){var f=W();try{return V(a)(b,c,d,e)}catch(h){X(f);if(h!==h+0)throw h;Y(1,0)}}function ld(a,b,c,d,e,f){var h=W();try{V(a)(b,c,d,e,f)}catch(k){X(h);if(k!==k+0)throw k;Y(1,0)}}function Nc(a,b,c){var d=W();try{return V(a)(b,c)}catch(e){X(d);if(e!==e+0)throw e;Y(1,0)}}function Sc(a,b,c,d,e,f){var h=W();try{return V(a)(b,c,d,e,f)}catch(k){X(h);if(k!==k+0)throw k;Y(1,0)}}
function md(a,b,c,d,e,f,h){var k=W();try{V(a)(b,c,d,e,f,h)}catch(p){X(k);if(p!==p+0)throw p;Y(1,0)}}function Tc(a,b,c,d,e,f,h){var k=W();try{return V(a)(b,c,d,e,f,h)}catch(p){X(k);if(p!==p+0)throw p;Y(1,0)}}function nd(a,b,c,d,e,f,h,k){var p=W();try{V(a)(b,c,d,e,f,h,k)}catch(n){X(p);if(n!==n+0)throw n;Y(1,0)}}function Jc(a,b){var c=W();try{return V(a)(b)}catch(d){X(c);if(d!==d+0)throw d;Y(1,0)}}
function Rc(a,b,c,d,e,f){var h=W();try{return V(a)(b,c,d,e,f)}catch(k){X(h);if(k!==k+0)throw k;Y(1,0)}}function Wc(a,b,c,d,e,f,h,k){var p=W();try{return V(a)(b,c,d,e,f,h,k)}catch(n){X(p);if(n!==n+0)throw n;Y(1,0)}}function Xc(a,b,c,d,e,f,h,k,p,n,l,q){var z=W();try{return V(a)(b,c,d,e,f,h,k,p,n,l,q)}catch(B){X(z);if(B!==B+0)throw B;Y(1,0)}}function od(a,b,c,d,e,f,h,k,p,n,l){var q=W();try{V(a)(b,c,d,e,f,h,k,p,n,l)}catch(z){X(q);if(z!==z+0)throw z;Y(1,0)}}
function pd(a,b,c,d,e,f,h,k,p,n,l,q,z,B,t,r){var A=W();try{V(a)(b,c,d,e,f,h,k,p,n,l,q,z,B,t,r)}catch(H){X(A);if(H!==H+0)throw H;Y(1,0)}}function Kc(a,b,c){var d=W();try{return V(a)(b,c)}catch(e){X(d);if(e!==e+0)throw e;Y(1,0)}}function ad(a,b,c,d){var e=W();try{return wd(a,b,c,d)}catch(f){X(e);if(f!==f+0)throw f;Y(1,0)}}function cd(a,b){var c=W();try{return xd(a,b)}catch(d){X(c);if(d!==d+0)throw d;Y(1,0)}}
function qd(a,b,c,d,e,f){var h=W();try{Ad(a,b,c,d,e,f)}catch(k){X(h);if(k!==k+0)throw k;Y(1,0)}}function sd(a,b,c,d,e,f,h){var k=W();try{Bd(a,b,c,d,e,f,h)}catch(p){X(k);if(p!==p+0)throw p;Y(1,0)}}function td(a,b,c,d){var e=W();try{Cd(a,b,c,d)}catch(f){X(e);if(f!==f+0)throw f;Y(1,0)}}function rd(a,b,c,d,e,f){var h=W();try{Dd(a,b,c,d,e,f)}catch(k){X(h);if(k!==k+0)throw k;Y(1,0)}}function dd(a,b,c){var d=W();try{return Ed(a,b,c)}catch(e){X(d);if(e!==e+0)throw e;Y(1,0)}}
function bd(a){var b=W();try{return yd(a)}catch(c){X(b);if(c!==c+0)throw c;Y(1,0)}}function $c(a,b,c,d,e){var f=W();try{return Gd(a,b,c,d,e)}catch(h){X(f);if(h!==h+0)throw h;Y(1,0)}}function Zc(a,b,c,d,e,f){var h=W();try{return Hd(a,b,c,d,e,f)}catch(k){X(h);if(k!==k+0)throw k;Y(1,0)}}function Yc(a,b,c,d,e,f,h){var k=W();try{return zd(a,b,c,d,e,f,h)}catch(p){X(k);if(p!==p+0)throw p;Y(1,0)}}function ed(a,b,c,d){var e=W();try{return Fd(a,b,c,d)}catch(f){X(e);if(f!==f+0)throw f;Y(1,0)}}
g.addRunDependency=Ja;g.removeRunDependency=Ka;g.cwrap=(a,b,c,d)=>{var e=!c||c.every(f=>"number"===f||"boolean"===f);return"string"!==b&&e&&!d?g["_"+a]:(...f)=>Ec(a,b,c,f)};g.FS_createPreloadedFile=Eb;g.FS_unlink=a=>cc(a);g.FS_createPath=ic;g.FS_createDevice=T;g.FS_createDataFile=(a,b,c,d,e,f)=>{Db(a,b,c,d,e,f)};g.FS_createLazyFile=lc;var Id;Ia=function Jd(){Id||Kd();Id||(Ia=Jd)};
function Ld(a=[]){var b=vd;a.unshift(ma);var c=a.length,d=zc(4*(c+1)),e=d;a.forEach(h=>{x[e>>2]=Ac(h);e+=4});x[e>>2]=0;try{var f=b(c,d);tc(f,!0)}catch(h){pc(h)}}
function Kd(){var a=ja;function b(){if(!Id&&(Id=!0,g.calledRun=!0,!va)){g.noFSInit||Jb||ha();Kb=!1;Sa(Ba);Sa(Ca);aa(g);g.onRuntimeInitialized?.();Md&&Ld(a);if(g.postRun)for("function"==typeof g.postRun&&(g.postRun=[g.postRun]);g.postRun.length;){var c=g.postRun.shift();Ea.unshift(c)}Sa(Ea)}}if(!(0<Ha)){if(g.preRun)for("function"==typeof g.preRun&&(g.preRun=[g.preRun]);g.preRun.length;)Ga();Sa(Aa);0<Ha||(g.setStatus?(g.setStatus("Running..."),setTimeout(()=>{setTimeout(()=>g.setStatus(""),1);b()},
1)):b())}}if(g.preInit)for("function"==typeof g.preInit&&(g.preInit=[g.preInit]);0<g.preInit.length;)g.preInit.pop()();var Md=!0;g.noInitialRun&&(Md=!1);Kd();moduleRtn=ca;


  return moduleRtn;
}
);
})();
if (typeof exports === 'object' && typeof module === 'object') {
  module.exports = Rapfi;
  // This default export looks redundant, but it allows TS to import this
  // commonjs style module.
  module.exports.default = Rapfi;
} else if (typeof define === 'function' && define['amd'])
  define([], () => Rapfi);
