using GomokuServer.Application.Games.Commands.Abstract;

namespace GomokuServer.Application.Games.Commands;

public record RegisteredResignCommand : ResignCommand;

public class RegisteredResignCommandHandler(
	IRegisteredGamesRepository _registeredGamesRepository,
	IRegisteredPlayersAwaitingGameRepository _playersAwaitingGameRepository)
	: ResignCommandHandler<RegisteredResignCommand>(_registeredGamesRepository, _playersAwaitingGameRepository);

public record AnonymousResignCommand : ResignCommand;

public class AnonymousResignCommandHandler(
	IAnonymousGamesRepository _anonymousGamesRepository,
	IAnonymousPlayersAwaitingGameRepository _anonymousPlayersAwaitingGameRepository)
	: ResignCommandHandler<AnonymousResignCommand>(_anonymousGamesRepository, _anonymousPlayersAwaitingGameRepository);
