name: Check for Codegen Changes

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  check-codegen:
    name: Check Code Generation
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.11.0'

      - name: Install dependencies (yarn)
        run: |
          cd $(CLIENT_DIR) && yarn install
          cd ./GomokuServer/src/GomokuServer.Api && dotnet restore

      - name: Install Tapper CLI
        run: dotnet tool install --global TypedSignalR.Client.TypeScript.Generator

      - name: Run Server
        run: dotnet run --configuration Release --project ./GomokuServer/src/GomokuServer.Api/GomokuServer.Api.csproj

      - name: Generate API Client and Hub Types
        run: |
          echo "Generating API client..."
          cd $(CLIENT_DIR) && yarn codegen
          
          echo "Generating hub types..."
          yarn generate-hub-types:server
          
          # Format with Prettier
          prettier --write src/api/hubs/

      - name: Check for Uncommitted Changes
        run: |
          git config --global --add safe.directory '*'
          if [[ $(git status --porcelain) ]]; then
            echo "Code generation produced changes!"
            git diff
            exit 1
          else
            echo "No changes detected from code generation."
          fi
