name: CI Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build_node:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.11.0'

#      - name: Install Chrome
#        run: sudo apt-get install -y chromium-browser

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.npm
            .yarn/cache
          key: ${{ runner.os }}-node-${{ hashFiles('**/GomokuClient/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: |
          cd GomokuClient
          yarn install

      #      - name: Run tests
      #        run: |
      #          cd GomokuClient
      #          node --stack-size=8192 $(which yarn) test --watch=false --browsers=ChromeHeadless
      #        env:
      #          CHROME_BIN: /usr/bin/chromium-browser

      - name: Build project
        run: |
          cd GomokuClient
          yarn build --configuration production

      - name: Archive production artifacts
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: production-artifacts
          path: GomokuClient/dist/

  # C# build job
  build_csharp:
    runs-on: ubuntu-latest
    env:
      WORKING_DIR: GomokuServer

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Build C# project
        run: dotnet build --configuration Release
        working-directory: ${{ env.WORKING_DIR }}

      - name: Run tests
        run: dotnet test --configuration Release
        working-directory: ${{ env.WORKING_DIR }}

      - name: Publish artifacts
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: csharp-build-artifacts
          path: GomokuServer/src/GomokuServer.Api/bin/Release/net8.0/
