name: CI Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build_node:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.11.0'

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.npm
            .yarn/cache
          key: ${{ runner.os }}-node-${{ hashFiles('**/GomokuClient/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: |
          cd GomokuClient
          yarn install

      - name: Run linting
        run: |
          cd GomokuClient
          yarn lint

      - name: Run Prettier
        run: |
          cd GomokuClient
          yarn format:check

      - name: Run typecheck
        run: |
          cd GomokuClient
          yarn typecheck

      - name: Build project
        run: |
          cd GomokuClient
          yarn build

      - name: Archive production artifacts
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: production-artifacts
          path: GomokuClient/dist/

  # C# build job
  build_csharp:
    runs-on: ubuntu-latest
    env:
      SERVER_DIR: GomokuServer

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Check formatting
        run: dotnet format --verify-no-changes ./GomokuServer/GomokuServer.sln

      - name: Build C# project
        run: dotnet build --configuration Release
        working-directory: ${{ env.SERVER_DIR }}

      - name: Run tests
        run: dotnet test --configuration Release
        working-directory: ${{ env.SERVER_DIR }}

      - name: Publish artifacts
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: csharp-build-artifacts
          path: ${{ env.SERVER_DIR }}/src/GomokuServer.Api/bin/Release/net8.0/
