name: Rapfi Integration Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Build and Test Docker Compose
        run: |
          docker-compose -f docker-compose.yml build
          docker-compose -f docker-compose.yml up --abort-on-container-exit
